galaxy.yml

Updated galaxy data
Galaxy basic galaxy data
```

Updated galaxy data

---

.yamllint
README.rst
galaxy.yml
test-requirements.txt
tox.ini

Galaxy push changes

---

galaxy.yml

- New Module Pull Request
```paste below
```

Updating the galaxy version

---

README.md
plugins/modules/sonic_api.py

Add README.md for sonic collection
dellemc_networking.sonic/README.md

Add README.md for sonic collection

---

README.md
changelogs/CHANGELOG.rst
changelogs/changelog.yaml
changelogs/config.yaml

Fix docs and add changelogs
ansible_collections/dellemc/sonic
```
ansible 2.10.0b1.post0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/administrator/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /home/administrator/JULY_ansible/ansible/lib/ansible
executable location = /home/administrator/JULY_ansible/ansible/bin/ansible
python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

Fix docs and add changelogs

---

README.md
galaxy.yml

Readme changes

---

README.md

Addresses #41.
Also fixes a couple of typos I saw. I didn't do a full copyedit, though, there may be other typos in there.
dellemc.enterprise_sonic collection

updates README to use FQCN in examples, fixes typos

---

README.md

Add a note in the "Releasing, Versioning and Deprecation" section
explaining the new branch designations for "development" and
"release" branches.
Repo/branch "README.md" file.
This PR implements changes that are identical to the corresponding README file
changes that have now been reviewed, approved, and merged to the "1.x" branch.
```paste below
```

Describe branch naming conventions

---

plugins/module_utils/network/sonic/argspec/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/facts/bgp_neighbors/bgp_neighbors.py
plugins/modules/sonic_bgp_neighbors.py
tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml

Added auth-password and description attrubutes to bgp neighbors module
sonic_bgp_neighbors
[bgp_neighbors_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8491159/bgp_neighbors_regression_report.pdf)
[sonic_bgp_neighbors_output (1).txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8491163/sonic_bgp_neighbors_output.1.txt)
[show_running_configuration_bgp_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8507542/show_running_configuration_bgp_output.txt)
[bgp_neighbors_facts_ut.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8507085/bgp_neighbors_facts_ut.log)
[plaintext_output.txt](https://github.com/ansible-collections/dellemc.enterprise_son …

Added auth-password and description attributes

---

plugins/module_utils/network/sonic/argspec/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/facts/bgp_neighbors/bgp_neighbors.py
plugins/modules/sonic_bgp_neighbors.py
tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml

Reverts ansible-collections/dellemc.enterprise_sonic#72

Revert "Added attributes to bgp_neighbors module"

---

tests/regression/roles/sonic_aaa/defaults/main.yml

This change modifies the testing of the "delete" test case for the
aaa resource module to enable testing of the functionality without
causing a failure in the "idempotent" test for the subsequent
merge/restore test case.
Problem analysis:
The "delete" test (Delete aaa properties; test_case_04) is
intended to verify functionality for deletion of an aaa configuration
attribute. Restoring the "fail_through" bool attribute after it has been
deleted, however, by changing it from the "null" (deleted) state back to a 
bool  value ("true", in this case) has the side effect in the SONiC functional
code of deleting the configuration for the other aaa configuration attributes
("group" and "local").
Because of this side effect when "restoring" the "fail_through"
attribute, the merge/restore test (aaa …

Fix the regression test failure for the aaa resource module.

---

plugins/module_utils/network/sonic/argspec/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/facts/bgp_neighbors/bgp_neighbors.py
plugins/modules/sonic_bgp_neighbors.py
tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml

PR 72 contains the test results and code review conversation relevant to PR 79:
https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/72

Revert "Revert "Added attributes to bgp_neighbors module""

---

changelogs/.plugin-cache.yaml
changelogs/CHANGELOG.rst
changelogs/archive_fragments/2.0.0/100-prefix_lists-resource-module.yaml
changelogs/archive_fragments/2.0.0/101-bgp-prefix_lists.yaml
changelogs/archive_fragments/2.0.0/102-playbook-example-updates.yaml
changelogs/archive_fragments/2.0.0/103-standard-interface-naming-and-other-bugfixes.yaml
changelogs/archive_fragments/2.0.0/105-vxlan-regression-test-fix.yaml
changelogs/archive_fragments/2.0.0/2.0.0.yaml
changelogs/archive_fragments/2.0.0/53-oc-yang-compliance.yaml
changelogs/archive_fragments/2.0.0/58-vxlan-primary-ip.yaml
changelogs/archive_fragments/2.0.0/60-bgp-regression-test_fixes.yaml
changelogs/archive_fragments/2.0.0/62-bgp-vxlan-primary-ip.yaml
changelogs/archive_fragments/2.0.0/63-bgp_af-route_advertise_list.yaml
changelogs/archive_fragments/2.0.0/67-bgp_neighbors-auth_pwd-and-neighbor_description.yaml
changelogs/archive_fragments/2.0.0/72-bgp_neighbors-add-attributes.yaml
changelogs/archive_fragments/2.0.0/76-CLI-command-prompt-answer-fix.yaml
changelogs/archive_fragments/2.0.0/78-aaa-regression-fix.yaml
changelogs/archive_fragments/2.0.0/81-add-bgp-peer-group-attributes.yaml
changelogs/archive_fragments/2.0.0/82-static_routes.yaml
changelogs/archive_fragments/2.0.0/85-regression-test-fixes.yaml
changelogs/archive_fragments/2.0.0/88-port_breakout-and-execution-environment.yaml
changelogs/archive_fragments/2.0.0/90-aaa-and-users-bugfix.yaml
changelogs/archive_fragments/2.0.0/98-vlans-description.yaml
changelogs/archive_fragments/2.0.0/99-ntp-resource-module.yaml
changelogs/changelog.yaml
changelogs/config.yaml
galaxy.yml
plugins/modules/sonic_prefix_lists.py

- Provide release note documentation and changelog fragments for the 2.0.0 release of the Dell
Enterprise SONiC Ansible collection.
- Correct the "version_added" field for the sonic_prefix_lists module.
(Change the specified version from 1.2.0 to 2.0.0.)
Release 2.0.0 changelogs
```paste below
```

Release notes 2.0.0

---

plugins/modules/sonic_ntp.py

SUMMARY
This is to change NTP module name.
ISSUE TYPE
COMPONENT NAME
sonic_ntp
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9529572/regression_test.log)
[regression-2022-09-08-10-42-13.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9529575/regression-2022-09-08-10-42-13.html.pdf)

Change NTP module name

---

galaxy.yml

Update the required ansible.netcommon version from `>=2.0.0` to `>=2.0.0,<5.0.0`
Dependency version

Update required ansible.netcommon version

---

docs/ADDITIONAL_INFORMATION.md

This PR has been raised as the original [PR#142](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/142) has been closed due deletion of head repository.
Since, the previous PR was not reviews. Request to review the PR and share your comment.

Additional information file under docs folder

---

tests/unit/modules/network/sonic/fixtures/sonic_bgp_af.yaml

When PR180 made changes in base code for fixing regression failures, it broke the UT cases. Fixing it now
BGP AF Unit Testing

Fix in bgp_af UT due to recent changes in bgp_af module

---

.github/PULL_REQUEST_TEMPLATE.md

This is PR is an extension of [PR#121](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/121) and [PR#139](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/139). We have added all the comments from PR121 to this PR and have commented it below. This new PR has been closed due deletion of old head repositories.
<strong>Kerry</strong> Thanks for creating these guideline. I have posted some minor comments/questions inline.
<strong>Kerry</strong> In the PR description, please provide any relevant details on recommended procedures and/or tools for measuring code coverage (if any).
<strong>KVSK</strong> We have commented the below statement under additional information section to handle this code coverage measurement. "Measure the code coverage before and …

Template for Pull Request

---

tests/unit/modules/network/sonic/fixtures/sonic_bgp.yaml
tests/unit/modules/network/sonic/test_sonic_bgp.py

Adding unit tests code for BGP module
BGP Unit Test Module

BGP Unit test code added

---

tests/unit/modules/network/sonic/fixtures/sonic_bgp_as_paths.yaml
tests/unit/modules/network/sonic/test_sonic_bgp_as_paths.py

BGP AS PATHS module unit test cases added
BGP AS PATHS UNIT TESTING

BGP AS PATHS module unit test cases added

---

tests/unit/modules/network/sonic/fixtures/sonic_bgp_communities.yaml
tests/unit/modules/network/sonic/test_sonic_bgp_communities.py

BGP Communities module unit testing code added
BGP Communities Unit Testing

BGP Communities module unit testing code added

---

tests/unit/modules/network/sonic/fixtures/sonic_bgp_ext_communities.yaml
tests/unit/modules/network/sonic/test_sonic_bgp_ext_communities.py

BGP Extended Communities Module Unit Testing Code Added
BGP Extended Communities Unit Testing

BGP Extended Communities Module Unit Testing Code Added

---

tests/unit/modules/network/sonic/fixtures/sonic_bgp_neighbors_af.yaml
tests/unit/modules/network/sonic/test_sonic_bgp_neighbors_af.py

BGP Neighbors Address Family Unit Test Code Added
BGP Neighbors Unit Testing

BGP Neighbors Address Family Unit Test Code Added

---

tests/unit/modules/network/sonic/fixtures/sonic_tacacs_server.yaml
tests/unit/modules/network/sonic/test_sonic_tacacs_server.py

Unit testing code for tacacs server module added
tacacs server module Unit testing

tacacs server unit testing code added

---

tests/unit/modules/network/sonic/fixtures/sonic_radius_server.yaml
tests/unit/modules/network/sonic/test_sonic_radius_server.py

Unit testing code for radius server module added
radius_server unit testing

radius server unit testing code added

---

tests/unit/modules/network/sonic/fixtures/sonic_users.yaml
tests/unit/modules/network/sonic/test_sonic_users.py

users module unit testing code added
users module unit testing

users module unit testing code added

---

plugins/module_utils/network/sonic/config/ntp/ntp.py

SUMMARY
This is to fix GitHub issue 205.
GitHub Issues
https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/205
ISSUE TYPE
COMPONENT NAME
sonic_ntp
OUTPUT
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11152595/regression_test.log)
[regression-2023-04-04-09-59-46.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11152603/regression-2023-04-04-09-59-46.html.pdf)
- unit test playbook: 
[ntp_unit_test.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11153512/ntp_unit_test.txt)
[unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11153490/unit_test.log) …

Fix GitHub issue 205

---

tests/unit/modules/network/sonic/fixtures/sonic_system.yaml
tests/unit/modules/network/sonic/test_sonic_system.py

Unit testing code for system module added
sonic_system Unit Testing

Unit testing code for system module added

---

plugins/module_utils/network/sonic/argspec/vxlans/vxlans.py
plugins/modules/sonic_vxlans.py
tests/unit/modules/network/sonic/fixtures/sonic_vxlans.yaml
tests/unit/modules/network/sonic/test_sonic_vxlans.py

unit testing code for vxlan module added
vxlan module unit testing

unit testing code for vxlan module added

---

tests/unit/modules/network/sonic/fixtures/sonic_static_routes.yaml
tests/unit/modules/network/sonic/test_sonic_static_routes.py

static routes unit testing code added
static routes unit testing

static routes unit testing code added

---

tests/unit/modules/network/sonic/fixtures/sonic_interfaces.yaml
tests/unit/modules/network/sonic/test_sonic_interfaces.py

Interfaces module Unit Test Code Added
Interfaces module Unit Testing

unit testing code for interfaces module added

---

tests/unit/modules/network/sonic/fixtures/sonic_mclag.yaml
tests/unit/modules/network/sonic/test_sonic_mclag.py

Unit testing code for mclag module added
mclag Unit Testing

Unit testing code for mclag module added

---

tests/unit/modules/network/sonic/fixtures/sonic_port_group.yaml
tests/unit/modules/network/sonic/test_sonic_port_group.py

Unit Testing for port_group module added
port_group Unit Testing

Ut port groups

---

tests/unit/modules/network/sonic/fixtures/sonic_port_breakout.yaml
tests/unit/modules/network/sonic/test_sonic_port_breakout.py

Unit Testing for port_breakout module added
port_breakout Unit Testing

Unit Testing for port_breakout module added

---

tests/unit/modules/network/sonic/fixtures/sonic_logging.yaml
tests/unit/modules/network/sonic/sonic_module.py
tests/unit/modules/network/sonic/test_sonic_logging.py

Unit testing for logging module added
logging Unit Testing

Unit testing for logging module added

---

plugins/module_utils/network/sonic/config/vrfs/vrfs.py

SUMMARY
This is to fix GitHub isuue 194.
GitHub Issues
https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/194
ISSUE TYPE
COMPONENT NAME
sonic_vrfs
OUTPUT
- regression test result:  
[regression-2023-04-10-10-09-12.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11192617/regression-2023-04-10-10-09-12.html.pdf)
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11192619/regression_test.log)
[unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11192623/unit_test.log)
[vrf_unit_test.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11192625/vrf_unit_test.txt) …

Fix GitHub issue 194

---

plugins/module_utils/network/sonic/config/l3_interfaces/l3_interfaces.py
tests/regression/roles/sonic_l3_interfaces/defaults/main.yml
tests/regression/roles/sonic_l3_interfaces/tasks/preparation_tests.yaml

Fixed typos in l3 interfaces config code that were causing improper deletion. Added checks to prevent NoneType not iiterable error.
| GitHub Issue #170  |
| |
sonic_l3_interfaces
[regression-2023-04-10-16-08-32.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11194688/regression-2023-04-10-16-08-32.html.pdf)
[l3_reg_output.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11194693/l3_reg_output.log)

Resolved l3 interfaces bug

---

tests/unit/modules/network/sonic/fixtures/sonic_bgp_neighbors.yaml

Enhance Bgp Neighbors UT as per the recent BGP neighbor module enhanced code.
BGP neighbors module underwent an enhancemnet w.r.t default checks. BGP Neighbors UT started failing after that. Corrrected those UT failures by ehancing the UT
BGP Neighbors Unit Testing

Enhance Bgp Neighbors UT as per the recent BGP neighbor module enhanced code

---

changelogs/fragments/246-bgp-af-replaced-overridden-support.yaml
plugins/module_utils/network/sonic/argspec/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/config/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/facts/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/utils/utils.py
plugins/modules/sonic_bgp_af.py
tests/regression/roles/sonic_bgp_af/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_bgp_af.yaml

- Add support for replaced, overridden states in `bgp_af` module.
- Add regression test cases to cover replaced and overridden states.
|  N/A |
- sonic_bgp_af
- Regression test HTML report:
[bgp_af_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11319858/bgp_af_regression_report.pdf)
- Regression test detailed log:
[bgp_af_regression_terminal_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11319877/bgp_af_regression_terminal_output.txt)

bgp_af - Add support for 'replaced' and 'overridden' states

---

plugins/module_utils/network/sonic/config/ip_neighbor/ip_neighbor.py

SUMMARY
This is to re-design ip_neighbor module "replaced" state according to newly specified "replaced" definition.
GitHub Issues
N/A
ISSUE TYPE
- 
COMPONENT NAME
sonic_ip_neighbor
- regression result: 
[regression-2023-05-01-10-17-42.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11366895/regression-2023-05-01-10-17-42.html.pdf)
- regression log: 
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11366899/regression_test.log)
Checklist:
How Has This Been Tested?
Tested with real SONIC systems.

Change ip_neighbor module replaced state design

---

changelogs/fragments/258-change-logging-module-source-interface-naming.yaml
plugins/module_utils/network/sonic/facts/logging/logging.py

SUMMARY
This is to fix sonic_logging module issue with source_interface.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_logging
OUTPUT
- regression result: 
[regression-2023-05-09-12-24-46.html.pdf](https://github.com/ansible-collections/d
Checklist:
How Has This Been Tested?
Tested with real SONIC system, executed regression and unit test cases.

Fix sonic_logging module regression issue

---

changelogs/fragments/119-lag_interfaces-port-name-fix.yaml
changelogs/fragments/130-vxlans-attribute-restriction-fix.yaml
changelogs/fragments/141-add-route-distinguisher-target-attributes-to-bgp-af-module.yaml
changelogs/fragments/160-sanity-check-errors-fix.yaml
changelogs/fragments/180-regression-failures-fix.yaml
changelogs/fragments/195-aaa-login-authentication.yaml
changelogs/fragments/201-bgp-af-modify-vni-advertise-fix.yaml
changelogs/fragments/231-l3-interfaces-delete-fix.yaml
changelogs/fragments/233-bgp-neighbors-defaults-fix.yaml

I added fragments for my past PRs that are apart of the 2.1.0 release.

Added fragments for 2.1.0

---

changelogs/fragments/244-added-rt-delay-attribute-to-bgp-module.yaml
plugins/module_utils/network/sonic/argspec/bgp/bgp.py
plugins/module_utils/network/sonic/config/bgp/bgp.py
plugins/module_utils/network/sonic/facts/bgp/bgp.py
plugins/modules/sonic_bgp.py
tests/regression/roles/sonic_bgp/defaults/main.yml
tests/regression/roles/sonic_bgp/templates/cli_test_case_01.cfg
tests/unit/modules/network/sonic/fixtures/sonic_bgp.yaml

I updated the source code to support addition of route-map-process-delay attribute.
sonic_bgp
[regression-2023-04-21-10-26-59.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11298217/regression-2023-04-21-10-26-59.html.pdf)
[bgp_reg_output.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11298223/bgp_reg_output.log)
[show_running_bgp.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11298267/show_running_bgp.txt)

Added route-map-process-delay attribute to BGP module

---

changelogs/fragments/145-mclag-new-attributes.yaml
changelogs/fragments/146-vrf-mgmt-bug-fix.yaml
changelogs/fragments/148-dhcp-relay-unit-tests.yaml
changelogs/fragments/176-update-netcommon-version.yaml
changelogs/fragments/199-code-coverage-workflow-fix.yaml
changelogs/fragments/254-update-replace-methods.yaml
changelogs/fragments/262-vlan-mapping-bug-fix.yaml

Added missing fragments

---

changelogs/fragments/124-l2-interfaces-oc-yang-vlan-range-format-config-support.yaml
changelogs/fragments/149-l2-interfaces-vlan-trunk-range-support-for-playbooks.yaml
changelogs/fragments/172-module-utils-import-remove-empties-from-ansible-lib.yaml

Provide fragment files for the listed PRs to prepare for creation of release notes for the enterprise_sonic 2.1.0 release.

Fragment files for release 2.1.0: Covering PRs 124, 149, and 172

---

changelogs/fragments/269-revert-aaa-breaking-changes.yaml
playbooks/common_examples/sonic_aaa.yaml
plugins/module_utils/network/sonic/argspec/aaa/aaa.py
plugins/module_utils/network/sonic/config/aaa/aaa.py
plugins/module_utils/network/sonic/facts/aaa/aaa.py
plugins/modules/sonic_aaa.py
tests/regression/roles/sonic_aaa/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_aaa.yaml

Reverted aaa breaking changes since breaking changes aren't allowed in a minor release.
I reverted:
https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/195
sonic_aaa
[regression-2023-05-30-13-49-37.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11605875/regression-2023-05-30-13-49-37.html.pdf)
[aaa_reg_output.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11605877/aaa_reg_output.log)

Reverted aaa breaking changes

---

tests/regression/roles/sonic_l3_interfaces/defaults/main.yml
tests/regression/roles/sonic_logging/defaults/main.yml
tests/regression/roles/sonic_logging/tasks/cleanup_tests.yaml
tests/regression/roles/sonic_logging/tasks/preparation_tests.yaml
tests/regression/roles/sonic_vrfs/defaults/main.yml
tests/regression/roles/sonic_vrfs/tasks/cleanup_tests.yaml
tests/regression/roles/sonic_vrfs/tasks/main.yml
tests/regression/roles/sonic_vrfs/tasks/preparation_tests.yaml

Resolved regression failures
sonic_l3_interfaces
sonic_vrfs
sonic_logging
[regression-2023-06-02-15-16-19.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11639479/regression-2023-06-02-15-16-19.html.pdf)

Resolved regression failures

---

.github/workflows/ansible-test.yml
changelogs/fragments/274-add-changelog-workflow.yaml

Add a new github workflow to check for changelog fragement in PR using `ansible-network/github_actions`
|  N/A |
- workflow

[workflow] Add workflow to check for changelog fragments in PR

---

changelogs/fragments/298-add-mgmt-vrf-replaced-state-handling-in-vrfs-module.yaml
plugins/module_utils/network/sonic/config/vrfs/vrfs.py

SUMMARY
This is to add the handling for MGMT VRF replaced state.
ISSUE TYPE
COMPONENT NAME
sonic_vrfs
OUTPUT
[regression-2023-09-08-15-59-38.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12564180/regression-2023-09-08-15-59-38.html.pdf)
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12564181/regression_test.log)
[vrf_mgmt_ut_script.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12564183/vrf_mgmt_ut_script.txt)
[vrf_mgmt_ut.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12564184/vrf_mgmt_ut.log)
Checklist:
How Has This Been Tested?
- manually …

Add MGMT VRF replaced handling

---

changelogs/fragments/294-verbose-regression-report-template.yaml
tests/regression/roles/test_reports/templates/regression_html_report.j2

- Generate regression test report with increased verbosity if the specified ansible verbose level is `>= 3` (i.e -vvv and above)
- Format the regression test report template.
| N/A |
- regression test report
- Regression report: [regression-report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12521791/regression-report.pdf)
- Regression report with verbose enabled: [regression-report-verbose.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12521797/regression-report-verbose.pdf)

[test] Generate regression test report based on verbosity

---

changelogs/fragments/301-playbook-check-diff-modes-for-vlans-interfaces.yaml
plugins/module_utils/network/sonic/config/interfaces/interfaces.py
plugins/module_utils/network/sonic/config/vlans/vlans.py
tests/unit/modules/network/sonic/fixtures/sonic_interfaces.yaml

SUMMARY
This is check and diff modes support for sonic_vlans and sonic_interfaces resource modules.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_vlans, sonic_interfaces
OUTPUT
- vlans regression test result: 
[regression-2023-10-05-09-42-34.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12821687/regression-2023-10-05-09-42-34.html.pdf)
- vlans regression test log: 
[vlans_regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12821689/vlans_regression_test.log)
- vlans unit test script: 
[vlans.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12821693/vlans.txt)
- vlan unut test log: 
[vlans_unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic …

Vlans and interfaces resource modules check and diff modes support

---

changelogs/fragments/279-playbook-check-diff-modes-and-radius-server-implement.yaml
changelogs/fragments/281-playbook-check-diff-modes-for-ntp-module.yaml
changelogs/fragments/284-playbook-check-diff-modes-for-system-and-port-group-modules.yaml
changelogs/fragments/285-playbook-check-diff-modes-for-vrfs-logging-ip-neighbor.yaml
changelogs/fragments/301-playbook-check-diff-modes-for-vlans-interfaces.yaml
changelogs/fragments/303-playbook-check-diff-modes-for-l2-lag-interfaces.yaml

SUMMARY
This is to change fragment files to comply with Ansible criteria.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_radius_server, sonic_ntp, sonic_system, sonic_port_group, sonic_vrfs, sonic_logging, sonic_ip_neighbor
sonic_vlans, sonic_interfaces, sonic_l2_interfaces, sonic_lag_interfaces
OUTPUT:
N/A
Checklist:

Change fragment files to comply with Ansible criteria

---

changelogs/fragments/310-change-deleted-design-for-interfaces-module.yaml
plugins/module_utils/network/sonic/config/interfaces/interfaces.py
plugins/module_utils/network/sonic/config/users/users.py
plugins/module_utils/network/sonic/facts/interfaces/interfaces.py
plugins/module_utils/network/sonic/facts/stp/stp.py
plugins/module_utils/network/sonic/sonic.py
plugins/module_utils/network/sonic/utils/utils.py
tests/unit/modules/network/sonic/fixtures/sonic_interfaces.yaml
tests/unit/modules/network/sonic/test_sonic_interfaces.py

SUMMARY
This is to change deleted state design for interfaces module to make it be able to delete individual attribute.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
OUTPUT
- regression result: 
[regression-2023-11-16-09-29-00.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13382156/regression-2023-11-16-09-29-00.html.1.pdf)
- regression log: 
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13285087/regression_test.log)
[interfaces.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13285090/interfaces.txt)
[unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13285093/unit_test.log) …

Change deleted state design for interfaces module

---

changelogs/fragments/313-laybook-check-diff-modes-for-static-route.yaml
plugins/module_utils/network/sonic/config/static_routes/static_routes.py
plugins/module_utils/network/sonic/utils/formatted_diff_utils.py
plugins/module_utils/network/sonic/utils/utils.py
plugins/modules/sonic_static_routes.py
tests/unit/modules/network/sonic/fixtures/sonic_static_routes.yaml
tests/unit/modules/network/sonic/test_sonic_static_routes.py

SUMMARY
Add diff and check mode support for static_route resource module.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_static_route
OUTPUT
[regression-2023-11-27-11-03-13.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13479316/regression-2023-11-27-11-03-13.html.pdf)
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13479322/regression_test.log)
[unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13479324/unit_test.log)
- unit test script:
[static_routes.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13479327/static_routes.txt)
Checklist:
How Has This Been …

static_route module diff and check mode

---

changelogs/fragments/306-playbook-check-diff-modes-for-acls.yaml
plugins/module_utils/network/sonic/config/acl_interfaces/acl_interfaces.py
plugins/module_utils/network/sonic/config/l2_acls/l2_acls.py
plugins/module_utils/network/sonic/config/l3_acls/l3_acls.py
plugins/modules/sonic_acl_interfaces.py
plugins/modules/sonic_l2_acls.py
plugins/modules/sonic_l3_acls.py

SUMMARY
This is to add playbook diff and check modes support for sonic_acl_interfaces, sonic_l2_acls and sonic_l3_acls resource modules.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_interfaces, sonic_l2_acls, sonic_l3_acls
OUTPUT
- acl_interfaces regression result: 
[acl_interfaces_regression-2023-11-28-14-21-58.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13494011/acl_interfaces_regression-2023-11-28-14-21-58.html.pdf)
- acl_interfaces regression log: 
[acl_interfaces_regression.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207845/acl_interfaces_regression.log)
- acl_interfaces unit test script:
[acl_interfaces.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207849/ac …

Diff and check modes support for acl_interfaces l2_acls and l3_acls modules

---

tests/unit/modules/network/sonic/fixtures/sonic_acl_interfaces.yaml
tests/unit/modules/network/sonic/fixtures/sonic_l2_acls.yaml
tests/unit/modules/network/sonic/fixtures/sonic_l3_acls.yaml
tests/unit/modules/network/sonic/sonic_module.py
tests/unit/modules/network/sonic/test_sonic_acl_interfaces.py
tests/unit/modules/network/sonic/test_sonic_l2_acls.py
tests/unit/modules/network/sonic/test_sonic_l3_acls.py

Add UT for ACL modules - acl_interfaces, l2_acls and l3_acls.
| N/A |
- sonic_acl_interfaces
- sonic_l2_acls
- sonic_l3_acls

Add UT for ACL modules

---

changelogs/fragments/314-replaced-overridden-for-interfaces-module.yaml
plugins/module_utils/network/sonic/config/interfaces/interfaces.py
plugins/module_utils/network/sonic/facts/interfaces/interfaces.py
plugins/module_utils/network/sonic/utils/interfaces_util.py
plugins/modules/sonic_interfaces.py
tests/regression/roles/sonic_interfaces/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_interfaces.yaml
tests/unit/modules/network/sonic/test_sonic_interfaces.py

Added "replaced" and "overridden" states for the Interface module
| |
```paste below
```
[regression-2023-12-22-02-30-57.zip](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13746360/regression-2023-12-22-02-30-57.zip)

Interface - Add support for replaced and overridden states

---

changelogs/fragments/321-requirements-update-meta-runtime-ansible-version.yaml
meta/runtime.yml
tests/regression/hosts

Ansible has declared "end of life" for ansible-core versions older than version 2.14. For this reason, our most recent release was rejected due to an obsolete dependency declaration for ansible-core.
This change set updates the problematic dependency line and also upgrades the specified Python interpreter in our example inventory file (tests/regression/hosts) to the minimum required Python version for Ansible core version 2.14.
| |
N/A
requirements
```paste below
Regression test execution for an arbitrary module (dhcp_snooping):
```
[test_ansible_version_req_update_with_dhcp.pdf](https://github.com/ansible-collections/del …

Upgrade the enterprise_sonic collection Ansible core version requirement to a currently supported Ansible core version.

---

.github/workflows/code-coverage.yml
test-requirements.txt

Make the below changes in code coverage workflow:
- Update `actions/checkout` and `actions/setup-python` to versions that support node version 20.
- Use pytest directly for code coverage.
- Use `pytest-ansible` plugin instead of deprecated `pytest-ansible-units`.
| N/A |
- workflow
```paste below
```
```paste below
```

[workflow]: Update code coverage workflow

---

tests/unit/modules/network/sonic/sonic_module.py

In utils.  'get_device_interface_naming_mode' is called based on the value of global variable 'intf_naming_mode'.
If value of 'intf_naming_mode' is set earlier, the mock for 'get_device_interface_naming_mode' is not invoked resulting in test failure.
- 'intf_naming_mode' is patched (with '') in setUp to ensure that 'get_device_interface_naming_mode' is called for all test cases. 
|  N/A |
- UT
```paste below
```
```paste below
```

[UT] Fix 'get_device_interface_naming_mode' mock not taking effect

---

tests/regression/roles/sonic_users/defaults/main.yml

The regression test cases originally defined for the sonic_users module used a password of "admin". This is no longer accepted
in current SONiC images and was causing 14 of the 16 test sections to fail.
This change set does not modify any "functional" code. It just changes the password used in test cases to meet the updated
SONiC requirements.
| |
N/A
sonic_users
[sonic_users_regression_fix_regression_summary_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14621321/sonic_users_regression_fix_regression_summary_report.pdf)
```paste below
```
Please describe the tests that you ran to verify …

Fix invalid short passwords used for sonic_users regression test cases.

---

changelogs/fragments/354-prefix-lists-fix-replaced-idempotency.yaml
plugins/module_utils/network/sonic/config/prefix_lists/prefix_lists.py
plugins/module_utils/network/sonic/facts/prefix_lists/prefix_lists.py
tests/regression/roles/sonic_prefix_lists/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_prefix_lists.yaml
tests/unit/modules/network/sonic/test_sonic_prefix_lists.py

- Incorporate the below fixes in prefix_lists:
- In replaced, ensure that the specified prefix list is replaced with the provided configuration.
- Fix idempotency failure when `le` is specified as the maximum prefix length for that address family. 
- Add UT for replaced and overridden states.
- Update regression test cases.
|  N/A |
- sonic_prefix_lists
Regression reports with the updated test cases
- After fix : [prefix_lists_regression_report_with_fix.pdf](https://github.com/ansible-collection …

prefix_lists - Fix idempotency failure and 'replaced' state handling

---

changelogs/fragments/351-bgp-af-import-vrf-support.yaml
plugins/module_utils/network/sonic/argspec/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/config/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/facts/bgp_af/bgp_af.py
plugins/modules/sonic_bgp_af.py
tests/regression/roles/sonic_bgp_af/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_bgp_af.yaml

bgp_af - Add support for 'import vrf' commands
| N/A |
- sonic_bgp_af
Regression report: [bgp_af_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14556045/bgp_af_regression_report.pdf)
Regression terminal output: [bgp_af_regression_terminal_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14556047/bgp_af_regression_terminal_output.txt)

bgp_af - Add support for 'import vrf' commands

---

changelogs/fragments/350-playbook-check-diff-modes-for-bgp-modules.yaml
plugins/module_utils/network/sonic/config/bgp/bgp.py
plugins/module_utils/network/sonic/config/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/config/bgp_as_paths/bgp_as_paths.py
plugins/module_utils/network/sonic/config/bgp_communities/bgp_communities.py
plugins/module_utils/network/sonic/config/bgp_ext_communities/bgp_ext_communities.py
plugins/module_utils/network/sonic/utils/formatted_diff_utils.py
plugins/module_utils/network/sonic/utils/sort_config_util.py

Add check and diff modes support for some BGP modules. See below modules list.
N/A
sonic_bgp
sonic_bgp_af
sonic_bgp_as_paths
sonic_bgp_communities
sonic_bgp_ext_communities
- bgp regresiion result: 
[bgp_regression-2024-02-27-22-47-00.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14514562/bgp_regression-2024-02-27-22-47-00.html.pdf)
- bgp regression log: 
[bgp_regression.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14514565/bgp_regression.log)
- bgp unit test log: 
[bgp_unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14514571/bgp_unit_test.log)
- bgp_af regression result: 
[bgp_af_regression-2024-03-04-22-02-58.html.pdf](https://github.com/ansible-collections/dellemc. …

Add diff and check modes support for some BGP modules

---

changelogs/fragments/360-playbook-check-diff-modes-for-bgp-neighbors-and-af.yaml
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/bgp_neighbors_af/bgp_neighbors_af.py
plugins/module_utils/network/sonic/utils/formatted_diff_utils.py
plugins/module_utils/network/sonic/utils/utils.py
plugins/modules/sonic_bgp_neighbors.py
plugins/modules/sonic_bgp_neighbors_af.py

Add check and diff modes support for bgp_neighbors and bgp_neighbors_af modules.
(bgp_neighbors regression log is too big to upload, so separate it into two files to upload)
N/A
- sonic_bgp_neighbors
- sonic_bgp_neighbors_af
- [bgp_neighbors_regression-2024-03-11-22-41-18.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14706814/bgp_neighbors_regression-2024-03-11-22-41-18.html.pdf)
- [Uploading bgp_neighbors_regression_1.log…]()
- [Uploading bgp_neighbors_regression_2.log…]()
- [bgp_neighbors_unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14706818/bgp_neighbors_unit_test.log)
- [bgp_neighbors_af_regression-2024-03-13-20-04-17.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic …

Add bgp neighbors and af check and diff modes

---

tests/unit/modules/network/sonic/fixtures/sonic_interfaces.yaml
tests/unit/modules/network/sonic/fixtures/sonic_qos_buffer.yaml
tests/unit/modules/network/sonic/fixtures/sonic_qos_pfc.yaml
tests/unit/modules/network/sonic/fixtures/sonic_sflow.yaml

Fix UT failures observed in modules after updating the requests validation (#344).
| N/A |
- UT

[UT] Fix UT failures observed after updating the requests validation

---

changelogs/fragments/383-fix-state-implementation.yaml
plugins/module_utils/network/sonic/argspec/bfd/bfd.py
plugins/module_utils/network/sonic/argspec/mac/mac.py
plugins/module_utils/network/sonic/argspec/static_routes/static_routes.py
plugins/module_utils/network/sonic/config/bfd/bfd.py
plugins/module_utils/network/sonic/config/mac/mac.py
plugins/module_utils/network/sonic/config/static_routes/static_routes.py
plugins/module_utils/network/sonic/facts/bfd/bfd.py
plugins/module_utils/network/sonic/facts/mac/mac.py
plugins/module_utils/network/sonic/facts/static_routes/static_routes.py
plugins/modules/sonic_bfd.py
plugins/modules/sonic_mac.py
plugins/modules/sonic_static_routes.py
tests/regression/roles/sonic_bfd/tasks/main.yml
tests/regression/roles/sonic_static_routes/tasks/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_bfd.yaml
tests/unit/modules/network/sonic/fixtures/sonic_mac.yaml
tests/unit/modules/network/sonic/test_sonic_bfd.py
tests/unit/modules/network/sonic/test_sonic_mac.py

I fixed the state implementation bugs for BFD, MAC, and static routes modules. I also made minor updates to documentation for these modules.
- sonic_bfd
- sonic_mac
- sonic_static_routes
[regression-2024-05-21-10-09-22.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/15393410/regression-2024-05-21-10-09-22.html.pdf)
[diff_output.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/15393417/diff_output.log)

Fix bugs for BFD, MAC, and static routes modules

---

changelogs/fragments/384-add-route-maps-ut.yaml
tests/unit/modules/network/sonic/fixtures/sonic_route_maps.yaml
tests/unit/modules/network/sonic/test_sonic_route_maps.py

I added the UT for the route maps module.
sonic_route_maps

Add UT for route maps module

---

tests/regression/roles/sonic_bgp_neighbors_af/defaults/main.yml

Update 'sonic_bgp_neighbors_af' regression test cases to use appropriate interface names based on interface naming mode.
| N/A |
- sonic_bgp_neighbors_af
Regression report:
- native interface naming mode: [bgp_neighbors_af_native.pdf](https://github.com/user-attachments/files/15613147/bgp_neighbors_af_native.pdf)
- standard interface naming mode: [bgp_neighbors_af_standard.pdf](https://github.com/user-attachments/files/15613152/bgp_neighbors_af_standard.pdf)

[bgp_neighbors_af] Fix regression test cases

---

changelogs/fragments/391-fix-qos-pfc-bug.yaml
plugins/module_utils/network/sonic/config/qos_pfc/qos_pfc.py

A line of code accidentally got deleted and merged while addressing a sanity error.
https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/348/commits/bafb95512fcef8dbf0918ea1a9dbce5872321d4b
sonic_qos_pfc
[regression-2024-06-07-14-28-16.html.pdf](https://github.com/user-attachments/files/15745188/regression-2024-06-07-14-28-16.html.pdf)

Fix bug for QoS PFC module

---

changelogs/fragments/388-system-update-replaced-state.yaml
plugins/module_utils/network/sonic/config/system/system.py
plugins/module_utils/network/sonic/facts/system/system.py
tests/unit/modules/network/sonic/fixtures/sonic_system.yaml

Incorporate the below changes in `sonic_system` module:
- Update replaced state handling.
- Update UT cases.
| N/A |
- sonic_system
Regression report: [system_regression_report.pdf](https://github.com/user-attachments/files/15612585/system_regression_report.pdf)

[system] Update replaced state handling

---

changelogs/fragments/398-bgp-af-aggregate-address-support.yaml
plugins/module_utils/network/sonic/argspec/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/config/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/facts/bgp_af/bgp_af.py
plugins/modules/sonic_bgp_af.py
tests/regression/roles/sonic_bgp_af/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_bgp_af.yaml

I added aggregate address configuration support to the BGP AF module.
Please see [model PR](https://github.com/ansible-network/resource_module_models/pull/261).
|- #347  |
- sonic_bgp_af
[regression-2024-06-26-07-58-18.html.pdf](https://github.com/user-attachments/files/15991124/regression-2024-06-26-07-58-18.html.pdf)
[diff_output.log](https://github.com/user-attachments/files/15920726/diff_output.log)
[facts_gathering.log](https://github.com/user-attachments/files/15920731/facts_gathering.log)

Add aggregate address configuration support to BGP AF module

---

tests/regression/roles/sonic_ntp/defaults/main.yml
tests/regression/roles/sonic_ntp/tasks/cleanup_tests.yaml
tests/regression/roles/sonic_ntp/tasks/preparation_tests.yaml

This is to add data VRF support for NTP module
N/A
sonic_ntp
[regression-2024-06-26-15-47-02.html.pdf](https://github.com/user-attachments/files/15991748/regression-2024-06-26-15-47-02.html.pdf)
[regression.log](https://github.com/user-attachments/files/15991752/regression.log)
Run regression testing and unit testing

Data VRF support for NTP module

---

changelogs/fragments/400-bgp-af-update-replaced-state.yaml
plugins/module_utils/network/sonic/config/bgp_af/bgp_af.py
plugins/modules/sonic_bgp_af.py
tests/regression/roles/sonic_bgp_af/tasks/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_bgp_af.yaml
tests/unit/modules/network/sonic/test_sonic_bgp_af.py

Incorporate the below changes in `sonic_bgp_af` module:
- Update replaced state handling.
- Update UT cases.
|  N/A |
- sonic_bgp_af
Regression report - [bgp_af_regression_report-2024-06-19-14-08-48.pdf](https://github.com/user-attachments/files/15898064/bgp_af_regression_report-2024-06-19-14-08-48.pdf)

bgp_af - Update replaced state handling

---

changelogs/fragments/418-github-issue-416-fix.yaml
plugins/module_utils/network/sonic/config/bgp/bgp.py

This is to fix GitHub issue#416: https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/416
#416
sonic_bgp
[regression-2024-07-18-12-30-22.html.pdf](https://github.com/user-attachments/files/16313899/regression-2024-07-18-12-30-22.html.pdf)
[regression.log](https://github.com/user-attachments/files/16313900/regression.log)
Did unit testing and regression testing.

Fix GitHub issue#416

---

changelogs/fragments/422-update-ut-for-bgp-neighbors.yaml
tests/unit/modules/network/sonic/fixtures/sonic_bgp_neighbors.yaml

Fixing UT failure for overridden_01 testcase in BGP_neighbors module.
| |
- bgp_neighbors
```paste below
```
```paste below
```
- [] I have maintained at least 90% code coverage

Update UT for bgp_neighbors

---

changelogs/fragments/405-auditd-config.yaml
plugins/module_utils/network/sonic/argspec/system/system.py
plugins/module_utils/network/sonic/config/system/system.py
plugins/module_utils/network/sonic/facts/system/system.py
plugins/modules/sonic_system.py
tests/regression/roles/sonic_system/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_system.yaml

Configure audit rules.
Auditd feature support.
NA
sonic_system
[regression-2024-07-11-21-39-18.html.pdf](https://github.com/user-attachments/files/16183856/regression-2024-07-11-21-39-18.html.pdf)
[regression-2024-08-09-19-39-06.html.pdf](https://github.com/user-attachments/files/16566245/regression-2024-08-09-19-39-06.html.pdf)
```paste below
```

Auditd feature support

---

changelogs/fragments/429-cliconf-doc-fix.yaml
plugins/cliconf/sonic.py

The description for the cliconf plugin in the SONiC collection originally referred to OS10 instead of SONiC as the target NOS. This reference was inherited from the OS10 Ansible collection from which it was initially derived. This change corrects that inaccuracy to specify SONiC as the intended NOS on which this plugin in the enterprise_sonic Ansible resource module collection can be used.
| |
N/A
cliconf
```paste below
```
Documentation change only: No functional testing is needed.
```paste below
```
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test …

Correct the cliconf description to reference SONiC instead of OS10.

---

changelogs/fragments/443-update-regex-edit-config.yaml
plugins/httpapi/sonic.py

I updated the regex search expression for 'not found' error message  to accommodate variations in SONiC code.
httpapi sonic.py
Facts gathering  log  before change:
[before_facts.txt](https://github.com/user-attachments/files/16805551/before_facts.txt)
Facts gathering log after change:
[after_facts.txt](https://github.com/user-attachments/files/16805553/after_facts.txt)

Update regex expression in edit_config method

---

changelogs/fragments/465-update-qos-wred-test-case.yaml
tests/regression/roles/sonic_qos_wred/defaults/main.yml

I updated QoS WRED regression test case based on SONiC code changes.
sonic_qos_wred
[regression-2024-10-08-12-49-16.html.pdf](https://github.com/user-attachments/files/17298608/regression-2024-10-08-12-49-16.html.pdf)

Update QoS WRED regression test case based on SONiC code changes

---

changelogs/fragments/463-mclag-prereq-member-deletion.yaml
plugins/module_utils/network/sonic/config/mclag/mclag.py
tests/unit/modules/network/sonic/fixtures/sonic_mclag.yaml

…
This change is provided to fix a regression test failure and is needed for correct mclag "delete all" handling with the revised Transformer implementation for container deletion.
| |
N/A
sonic_mclag
MCLAG passing regression test after incorporating the proposed change:
[mclag prereq member delete regression summary.pdf](https://github.com/user-attachments/files/17289585/mclag.prereq.member.delete.regression.summary.pdf)
```paste below
```
Verify that the previously failing mclag regression …

Delete any existing mclag PortChannel "members" before attempting to delete the entire mclag domain

---

changelogs/fragments/472-qos-interfaces-deletion-bugfix.yaml
changelogs/fragments/473-qos-interfaces-deletion-bugfix.yaml
plugins/module_utils/network/sonic/config/qos_interfaces/qos_interfaces.py

The delete commands were not being updated properly for deleted state so I corrected this issue.
sonic_qos_interfaces
[regression-2024-10-21-14-45-14.html.pdf](https://github.com/user-attachments/files/17467275/regression-2024-10-21-14-45-14.html.pdf)

Fix command deletion for QoS interfaces module

---

changelogs/fragments/481-radius_server-regression-test-hostname.yaml
changelogs/fragments/482-radius_server-regression-test-hostname.yaml
playbooks/common_examples/sonic_aaa.yaml
plugins/modules/sonic_radius_server.py
tests/regression/roles/sonic_radius_server/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_radius_server.yaml

…regex spec.
A recent SONiC code change modified the validation for the format of the host name used for radius server host configuration.
This change caused many of the enterprise_sonic radius server regression tests to fail.
This change set modifies the host names used in radius server regression and unit tests to conform to the new
host name format requirements. It also adds a description to the radius_server "module" file to explain the new
requirements for radius server host names.
| |
N/A
sonic_radius_server
Regression test summary output with the fix installed: …

Match radius server host name format in tests to new SONiC host name requirements.

---

changelogs/fragments/492-tests-sanity-ignore-action-plugin-for-ansible-2.20.yaml
tests/sanity/ignore-2.20.txt

Add a sanity "ignore" file for Ansible release 2.20 to ignore absence of a documentation "module" file corresponding to the sonic.py action plugin. (This plugin has no configuration options to document. It is the standalone "base" action plugin for the enterprise_sonic resource module collection.)
| |
N/A
tests
N/A
```paste below
```
- Re-run the previously failing sanity tests to verify that they now pass.
```
All checks have passed
19 successful checks
```

Ignore the Ansible 2.20 sanity failure for a missing module corresponding to the sonic.py action plugin.

---

tests/regression/roles/sonic_image_management/tasks/cleanup_files.yml
tests/regression/roles/sonic_image_management/tasks/image_verify.yml
tests/regression/roles/sonic_image_management/tasks/main.yml
tests/regression/roles/sonic_image_management/tasks/preparation_tests.yml

Added the tasks in regression tests to transfer the artifacts to the device.
For image verification tests, artifacts will be copied to the switch in a new directory and once the validations are completed, the artifacts copied will be deleted.
| N/A |
sonic_image_management
Regression report:
[regression-2024-11-25-11-41-07.pdf](https://github.com/user-attachments/files/17898163/regression-2024-11-25-11-41-07.pdf)

Update SONiC Image Management module tests

---

changelogs/fragments/517-fix-stp-check-mode.yaml
plugins/module_utils/network/sonic/config/stp/stp.py
tests/regression/roles/sonic_stp/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_stp.yaml
tests/unit/modules/network/sonic/test_sonic_stp.py

I fixed the STP check mode bug.
| GitHub Issue #502 |
sonic_stp
[regression-2025-02-28-15-24-09.html.pdf](https://github.com/user-attachments/files/19034184/regression-2025-02-28-15-24-09.html.pdf)
Check with diff mode playbook logs:
[before_bugfix.txt](https://github.com/user-attachments/files/19018288/before_bugfix.txt)
[after_bugfix.txt](https://github.com/user-attachments/files/19018289/after_bugfix.txt)
```paste below
```

Fix STP check mode bug

---

changelogs/fragments/541-ospf-area-bugfix.yaml
plugins/module_utils/network/sonic/config/ospf_area/ospf_area.py
plugins/modules/sonic_ospf_area.py
tests/regression/roles/sonic_ospf_area/defaults/main.yml
tests/regression/roles/sonic_ospf_area/tasks/cleanup_tests.yaml
tests/regression/roles/sonic_ospf_area/tasks/main.yml
tests/regression/roles/sonic_ospf_area/tasks/preparation_tests.yaml
tests/regression/roles/sonic_ospf_area/tasks/tasks_template.yaml
tests/unit/modules/network/sonic/fixtures/sonic_ospf_area.yaml

Fixed bug for OSPF area caused by SONiC code changes.
sonic_ospf_area
[regression-2025-04-03-13-56-32.html.pdf](https://github.com/user-attachments/files/19594677/regression-2025-04-03-13-56-32.html.pdf)

Bugfix for OSPF area

---

changelogs/fragments/543-qos-buffer-bugfix.yaml
plugins/httpapi/sonic.py
plugins/module_utils/network/sonic/config/qos_buffer/qos_buffer.py
plugins/modules/sonic_qos_buffer.py
tests/regression/roles/sonic_qos_buffer/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_qos_buffer.yaml
tests/unit/modules/network/sonic/test_sonic_qos_buffer.py

I updated the QoS buffer module to accommodate the CVL error handling changes  in SONiC. Static or dynamic threshold is required when configuring a buffer. 
- 
sonic_qos_buffer
[regression-2025-04-07-15-24-59.html.pdf](https://github.com/user-attachments/files/19639906/regression-2025-04-07-15-24-59.html.pdf)
- [] I have maintained at least 90% code coverage

Bugfix for QoS buffer module

---

changelogs/fragments/558-dcbx-symlink.yaml
meta/runtime.yml
plugins/action/dcbx.py

I added a symlink for dcbx module.
- Bug Pull Request
sonic_dcbx
[regression-2025-05-05-16-59-06.html.pdf](https://github.com/user-attachments/files/20051274/regression-2025-05-05-16-59-06.html.pdf)
- [] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.

Add symlink for dcbx

---

changelogs/fragments/532-aaa-mfa-support.yaml
plugins/module_utils/network/sonic/argspec/aaa/aaa.py
plugins/module_utils/network/sonic/config/aaa/aaa.py
plugins/module_utils/network/sonic/facts/aaa/aaa.py
plugins/modules/sonic_aaa.py
tests/regression/roles/sonic_aaa/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_aaa.yaml

**SUMMARY**
Added MFA (Multi-Factor Authentication) support to the AAA module.
**ISSUE TYPE**
**COMPONENT NAME**
- sonic_aaa
**OUTPUT**
[aaa_mfa_regression_report.pdf](https://github.com/user-attachments/files/19970133/aaa_mfa_regression_report.pdf)
**Checklist:**

Update AAA module with MFA changes

---

changelogs/fragments/562-adjust-txrx-clock-freq.yaml
plugins/module_utils/network/sonic/argspec/system/system.py
plugins/module_utils/network/sonic/config/system/system.py
plugins/module_utils/network/sonic/facts/system/system.py
plugins/modules/sonic_system.py
tests/regression/roles/sonic_system/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_system.yaml

Add support for Tx/Rx clock frequency adjustment
| |
- sonic_system
[Ansible_regression-2025-05-23-15-26-05.pdf](https://github.com/user-attachments/files/20438793/Ansible_regression-2025-05-23-15-26-05.pdf)

Add support for Clock frequency adjust TxRx PPM

---

changelogs/fragments/575-interfaces-bugfix.yaml
plugins/module_utils/network/sonic/config/interfaces/interfaces.py
plugins/module_utils/network/sonic/utils/interfaces_util.py
tests/regression/roles/common/defaults/main.yml
tests/regression/roles/sonic_interfaces/defaults/main.yml
tests/regression/roles/sonic_interfaces/meta/main.yaml
tests/regression/roles/sonic_interfaces/tasks/cleanup.yaml
tests/regression/roles/sonic_interfaces/tasks/main.yml
tests/regression/roles/sonic_interfaces/tasks/preparation_tests.yaml
tests/regression/roles/sonic_interfaces/tasks/tasks_template.yaml
tests/unit/modules/network/sonic/fixtures/sonic_interfaces.yaml

- I fixed the port-group interface error handling for speed configuration
- I updated the common default interface variables to map to the same interface in standard and native modes and updated some of the interface variables to map to non port-group interfaces.
- I fixed the test directory ansible-lint errors.
Failing test report with updated error message:
[regression-2025-07-17-12-36-05.html.pdf](https://github.com/user-attachments/files/21306825/regression-2025-07-17-12-36-05.html.pdf)
Passing test report:
[regression-2025-07-22-14-49-31.html.pdf](https://github.com/user-attachments/files/21376253/regression-2025-07-22-14-49-31.html.pdf)
Ansible-lint output:
[ansible_lint.txt](https://github.com/user-attachments/files/21306849/ansible_lint.txt)

sonic_interfaces- Fix port-group interface error handling for speed configuration
