ansible-collections/dellemc.enterprise_sonic

README.md

The suggested content is in INI format, so reflect that with the file extension so Ansible is happy.
The suggested `inventory.yaml` is not using Ansible YAML inventory format but rather the INI format.
README

Rename inventory.yaml to ini

---

plugins/module_utils/network/sonic/argspec/bgp_as_paths/bgp_as_paths.py
plugins/module_utils/network/sonic/config/aaa/aaa.py
plugins/module_utils/network/sonic/config/bgp/bgp.py
plugins/module_utils/network/sonic/config/bgp_as_paths/bgp_as_paths.py
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/bgp_neighbors_af/bgp_neighbors_af.py
plugins/module_utils/network/sonic/config/radius_server/radius_server.py
plugins/module_utils/network/sonic/facts/bgp_as_paths/bgp_as_paths.py
plugins/module_utils/network/sonic/facts/bgp_neighbors_af/bgp_neighbors_af.py
plugins/module_utils/network/sonic/facts/tacacs_server/tacacs_server.py
plugins/modules/sonic_bgp_as_paths.py
tests/regression/roles/sonic_bgp_as_paths/defaults/main.yml
tests/regression/roles/sonic_radius_server/defaults/main.yml
tests/regression/roles/sonic_tacacs_server/defaults/main.yml
tests/sanity/ignore-2.13.txt

- Added a permit attribute to the bgp_as_paths module and updated argspec, config, facts, and test cases accordingly
- Fixed retransmit-attempts bug for radius_server
- Fixed timeout bug for tacacs server
- Removed key attribute from server testcases since there is no key decryption
- Fixes #SNC-14120
- Fixes #SNC-13726
- sonic_bgp_as_paths
- sonic_radius_server
- sonic_tacacs_server
[logs.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/7463989/logs.pdf)
Final pre-merge passing regression results:
[shade_bgp_pr_regression_log_2021_1109_1138.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/7507653/shade_bgp_pr_regression_log_2021_1109_1138.txt)

Fixed bgp as path and authentication radius and tacacs bugs for 3.4

---

README.md
plugins/modules/sonic_command.py
plugins/modules/sonic_facts.py

Add a note to the "Releasing, Versioning and Deprecation" section of the README file explaining the new branch designations for "development" and "release" branches. This is intended for reference by customers to ensure that they are using only official release versions in production.
Repo/branch "README.md" file.
This PR (on the "1.x" branch) is intended for discussion purposes and incorporation of review comments before submitting a PR with the agreed-upon wording for the "main" branch.
```paste below
```

Describe branch naming conventions

---

plugins/module_utils/network/sonic/argspec/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/config/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/facts/bgp_af/bgp_af.py
plugins/modules/sonic_bgp_af.py
tests/regression/roles/sonic_bgp_af/defaults/main.yml

- The advertise-list in the OC yang was removed so the advertise_prefix in the sonic_bgp_af module needed to be removed.
- Attributes in the actioner were changed to int so those attributes were changed to int in the sonic_bgp_neighbors module
sonic_bgp_af, sonic_bgp_neighbors
[regression-2022-02-03-10-45-58.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8006609/regression-2022-02-03-10-45-58.pdf)
[bgp_af_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8007057/bgp_af_regression_report.pdf)

Fixed BGP regression failure bugs

---

plugins/module_utils/network/sonic/argspec/vxlans/vxlans.py
plugins/module_utils/network/sonic/config/vxlans/vxlans.py
plugins/module_utils/network/sonic/facts/vxlans/vxlans.py
plugins/modules/sonic_vxlans.py
tests/regression/roles/sonic_vxlan/defaults/main.yml

This change set provides the modifications needed to configure the
"primary-ip" address attribute for vxlan vtep interfaces, including
the ability to modify the existing value of the attribute, and to
delete the attribute.
It also adds regression test cases for adding, modifying, and
deleting primary-ip address configuration.
dellemc.enterprise_sonic (sonic_vxlans)
These changes provide the functionality for configuration and testing of "primary-ip"
address configuration for the sonic_vxlans module. For full functionality, the
co-requisite BGP configuration capability is also required.
```paste below
```
Dell Enterprise SONiC Ansible regression results for sonic_vxlans after adding
these changes:
[regression-primary_ip_pass_2022-02-01-21-44-13.pdf](https://github.com …

Add primary-ip configuration support for the sonic_vxlans module

---

plugins/module_utils/network/sonic/utils/utils.py
plugins/modules/sonic_command.py
plugins/modules/sonic_config.py
tests/regression/roles/sonic_config/defaults/main.yml
tests/regression/roles/sonic_config/tasks/backup.yaml

Root cause analysis:
Commands containing  a "prompt/answer" sequence require
the user to specify a dictionary containing the command, prompt,
and "answer" (for the prompt). The previously existing handling enclosed the
entire command dictionary (containing the "command", "prompt",
and "answer" key/value pairs) in quotes as the value for an
unintended outer "command" key. The other items in the
dictionary input to the "send_command" API (for sending
commands to a device) were set to defaults (for exec commands)
or left unspecified (for configuration commands).
For example:
- Ansible "module" contents from parsing a playbook that specified
an exec command "list" containing a single command/prompt/answer sequence:
-----------------------------
["{'command': 'image remove all', 'prompt': …

Fix problems in handling of CLI "exec" mode and "config" mode commands with prompts.

---

plugins/module_utils/network/sonic/utils/utils.py
plugins/modules/sonic_command.py
plugins/modules/sonic_config.py
tests/regression/roles/sonic_config/defaults/main.yml
tests/regression/roles/sonic_config/tasks/backup.yaml

REF: Branch 1.x PR:
https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/71
Root cause analysis:
Commands containing a "prompt/answer" sequence require
the user to specify a dictionary containing the command, prompt,
and "answer" (for the prompt). The previously existing handling enclosed the
entire command dictionary (containing the "command", "prompt",
and "answer" key/value pairs) in quotes as the value for an
unintended outer "command" key. The other items in the
dictionary input to the "send_command" API (for sending
commands to a device) were set to defaults (for exec commands)
or left unspecified (for configuration commands).
For example:
- Ansible "module" contents from parsing a playbook that specified
an exec command "list" containing a single …

Double commit to "main" branch: CLI command prompt/answer fix

---

plugins/module_utils/network/sonic/argspec/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/facts/bgp_neighbors/bgp_neighbors.py
plugins/modules/sonic_bgp_neighbors.py
tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml

I added the following OC attributes to the bgp_neighbors module:
bfd: check-control-plane-failure, enabled, bfd-profile
disable-ebgp-connected-route-check
dont-negotiate-capability
ebgp-multihop : enabled, multihop-ttl
enforce-first-as 
enforce-multihop 
local-as
local-as-no-prepend
local-as-replace-as
override-capability 
passive-mode
peer-port
shutdown-message
solo-peer
strict-capability-match
timers: connect-retry
ttl-security-hops
v6only
bgp_neighbors
[bgp_neighbors_output (3).log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8653529/bgp_neighbors_output.3.log)
[bgp_neighbors_facts_UT (1).log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8653421/bgp_neighbors_facts_UT.1.log) …

Added attributes to bgp_neighbors module

---

tests/regression/roles/sonic_aaa/defaults/main.yml

(Double commit: Also committed to the "main" branch)
This change modifies the testing of the "delete" test case for the
aaa resource module to enable testing of the functionality without
causing a failure in the "idempotent" test for the subsequent
merge/restore test case.
Problem analysis:
The "delete" test (Delete aaa properties; test_case_04) is
intended to verify functionality for deletion of an aaa configuration
attribute. Restoring the "fail_through" bool attribute after it has been
deleted, however, by changing it from the "null" (deleted) state back to a 
bool  value ("true", in this case) has the side effect in the SONiC functional
code of deleting the configuration for the other aaa configuration attributes
("group" and "local").
Because of this side effect when "restoring" the …

Fix the regression test failure for the aaa resource module.

---

plugins/module_utils/network/sonic/argspec/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/facts/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/utils/bgp_utils.py
plugins/modules/sonic_bgp_neighbors.py
tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml

I added the following OC attributes to the bgp_neighbors module for peer groups:
bfd: check-control-plane-failure, enabled, bfd-profile
disable-ebgp-connected-route-check
dont-negotiate-capability
ebgp-multihop : enabled, multihop-ttl
enforce-first-as
enforce-multihop
local address
local-as
local-as-no-prepend
local-as-replace-as
override-capability
passive-mode
pg-description
shutdown-message
solo-peer
strict-capability-match
timers: connect-retry
ttl-security-hops
sonic_bgp_neighbors
[show_running_configuration_bgp_pg_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8673691/show_running_configuration_bgp_pg_output.txt)

Added missing attributes to BGP neighbors peer group

---

README.md

Add information on mapping Dell Enterprise SONiC release image versions to the corresponding supporting Ansible Enterprise SONiC collection release versions.
I have received feedback from users that it was difficult to determine from our README file the mapping between Dell Enterprise SONiC release image versions and the corresponding supporting Ansible Enterprise SONiC collection release versions.
This change places the information closer to the top of the README file and provides explicit mapping of versions to make it easier for users to find this information.
```paste below
```

Ansible README.md file: Describe mapping of SONiC to Ansible release versions

---

README.md

Add information on mapping Dell Enterprise SONiC release image versions to the corresponding supporting Ansible Enterprise SONiC collection release versions.
I have received feedback from users that it was difficult to determine from our README file the mapping between Dell Enterprise SONiC release image versions and the corresponding supporting Ansible Enterprise SONiC collection release versions.
This change places the information closer to the top of the README file and provides explicit mapping of versions to make it easier for users to find this information.
```paste below
```

README.md file: Add release mapping information

---

tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml
tests/regression/roles/sonic_system/defaults/main.yml
tests/regression/roles/sonic_system/tasks/main.yml
tests/regression/roles/sonic_system/tasks/preparation_tests.yaml
tests/regression/roles/sonic_vxlan/defaults/main.yml

Resolved regression failures for:
- sonic_bgp_neighbors: I updated the pwd value due to encryption/decryption method changes.
- sonic_system: The initial delete all test case failed because there was nothing to delete so I added preparation tests and moved the delete all test case to the end of the playbook.
- sonic_vxlan: The test case failed because specified attributes were already deleted in the previous test case so I removed repetitive delete test case.
sonic_bgp_neighbors, sonic_system, sonic_vxlan
[regression-2022-05-20-16-39-11.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8745801/regression-2022-05-20-16-39-11.html.pdf)
[vxlan_output.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8745806/vxlan_out …

Resolved regression failures against 4.x

---

meta/execution-environment.yml
tests/regression/roles/sonic_system/defaults/main.yml
tests/regression/roles/sonic_system/tasks/main.yml
tests/regression/roles/sonic_system/tasks/preparation_tests.yaml

I resolved the sonic_system playbook failure. The failure was due to deletion of non existing config.
- Bug Fix Pull Request
sonic_system
[regression-2022-05-25-10-14-51.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8773387/regression-2022-05-25-10-14-51.html.pdf)

 Double commit for system playbook failure fix 

---

changelogs/.plugin-cache.yaml
changelogs/CHANGELOG.rst
changelogs/archive_fragments/1.1.1/1.1.1.yaml
changelogs/archive_fragments/1.1.1/51-add-stable-2.12-to-CI-test-matrix.yaml
changelogs/archive_fragments/1.1.1/52-bgp-as_path-attributes-and-radius-tacacs-auth-fixes.yaml
changelogs/archive_fragments/1.1.1/54-README-branch-naming.yaml
changelogs/archive_fragments/1.1.1/69-bgp-neighbors-password-and-description.yaml
changelogs/archive_fragments/1.1.1/71-cli-prompt-answer-handling.yaml
changelogs/archive_fragments/1.1.1/80-aaa-regression-test-fix.yaml
changelogs/archive_fragments/1.1.1/84-README-mapping-SONiC-releases-to-ansible-branches.yaml
changelogs/archive_fragments/1.1.1/87-system-regression-test-fix.yaml
changelogs/archive_fragments/1.1.1/89-execution-environment.yaml
changelogs/archive_fragments/1.1.1/91-add-stable-2.13-to-CI-test-matrix.yaml
changelogs/changelog.yaml
changelogs/config.yaml
galaxy.yml

This change set contains the archive source fragments used for generating
the Ansible release changelog, the generated changelog, and other
files generated by the antsibull-changelog tool for the release.
The galaxy.yml file and the changelogs/config.yaml file have also
been updated to specify the new galaxy version information, to add
new authors for the Dell SONiC Enterprise Ansible collection and to save
changelog fragments in an archive folder.
Test Results for the current 1.x branch (content to be released)
[1.1.1_release_all_modules_regression-2022-06-02-20-40-53.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8829565/1.1.1_release_all_modules_regression-2022-06-02-20-40-53.pdf)
```paste below
```

Create release 1.1.1 changelog and other Ansible release artifacts

---

plugins/module_utils/network/sonic/config/l2_interfaces/l2_interfaces.py

I added support for configuration of interfaces in standard naming mode.
Fixes #94 
sonic_l2_interfaces
[l2_interfaces_output.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8971803/l2_interfaces_output.log)
[regression-2022-06-23-15-31-07.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/8971806/regression-2022-06-23-15-31-07.html.pdf)

Added support for interface standard naming and port breakout mode in sonic_l2_interfaces

---

playbooks/bgp_l3_fabric/group_vars/leaf.yaml
playbooks/bgp_l3_fabric/group_vars/spine.yaml
playbooks/common_examples/sonic_bgp.yaml
playbooks/common_examples/sonic_bgp_communities.yaml
playbooks/common_examples/sonic_vxlans_config.yaml
plugins/modules/sonic_bgp_as_paths.py
tests/unit/utils/test_16_complex_list_with_dict_diff.yaml

I updated the example playbooks to reflect module updates.
sonic_bgp_as_paths
bgp_l3_fabric
common_examples

Updated example playbooks to reflect module updates

---

plugins/action/sonic.py
plugins/module_utils/network/sonic/config/bgp/bgp.py
plugins/module_utils/network/sonic/config/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/config/bgp_communities/bgp_communities.py
plugins/module_utils/network/sonic/config/bgp_ext_communities/bgp_ext_communities.py
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/sonic/config/lag_interfaces/lag_interfaces.py
plugins/module_utils/network/sonic/config/system/system.py
plugins/module_utils/network/sonic/facts/interfaces/interfaces.py
plugins/module_utils/network/sonic/facts/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/sonic/facts/l3_interfaces/l3_interfaces.py
plugins/module_utils/network/sonic/sonic.py
plugins/module_utils/network/sonic/utils/interfaces_util.py
tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml
tests/regression/roles/sonic_static_routes/defaults/main.yml
tests/regression/roles/sonic_static_routes/tasks/main.yml
tests/regression/roles/sonic_system/defaults/main.yml

- Removed AutoEscapeExtension since it is now built-in with Jinja 3.10
- Reverted the l2_interfaces standard naming bug fix changes
- Fixed system defaults bug and updated  system test cases
- Updated the regex expression in sonic.py to accommodate standard naming in port breakout mode 
- Updated bgp_neighbors test cases to accomodate encryption/decryption method changes and made use of interface variables
- Updated static_routes test cases to make use of interface variables and got rid of repetitive delete all task
- Resolved minor sanity check errors for bgp, bgp_af, bgp_neighbors, interfaces, l2_interfaces, l3_interfaces
bgp_communities
bgp_ext_communities
bgp_neighbors
interfaces_util
l2_interfaces
lag_interfaces
sonic
static_routes
system …

Addressed multiple bugs and updated test cases

---

plugins/module_utils/network/sonic/facts/ntp/ntp.py

SUMMARY
get-fact on NTP server brings in unsupported paramer. This is to fix the issue.
ISSUE TYPE
COMPONENT NAME
sonic_ntp
regression test log: 
[ntp_regression_log.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9472369/ntp_regression_log.log)
regression test result:
[regression-2022-09-01-10-10-23.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9472376/regression-2022-09-01-10-10-23.html.pdf)

Change NTP get fact on NTP servers

---

.github/workflows/ansible-test.yml
plugins/action/sonic.py
plugins/module_utils/network/sonic/config/bgp/bgp.py
plugins/module_utils/network/sonic/config/bgp_af/bgp_af.py
plugins/module_utils/network/sonic/config/bgp_communities/bgp_communities.py
plugins/module_utils/network/sonic/config/bgp_ext_communities/bgp_ext_communities.py
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/sonic/config/lag_interfaces/lag_interfaces.py
plugins/module_utils/network/sonic/facts/interfaces/interfaces.py
plugins/module_utils/network/sonic/facts/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/sonic/facts/l3_interfaces/l3_interfaces.py
plugins/module_utils/network/sonic/sonic.py
plugins/module_utils/network/sonic/utils/interfaces_util.py

- Fixed the regex expression in sonic.py to support standard naming with port breakout mode
- Removed AutoEscapeExtension in config since it is now built-in with Jinja 3.10
sonic.py
bgp_communities
bgp_ext_communities
lag_interfaces
interfaces_util
Executed in standard naming mode :
[regression-2022-09-06-12-58-22.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9500415/regression-2022-09-06-12-58-22.html.pdf)
test regression results for l2_interfaces after reverting standard naming bug fix :
[regression-2022-09-07-11-39-13.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9508797/regression-2022-09-07-11-39-13.html.pdf)

Fixed regex to support standard naming with port breakout mode and resolved other minor bugs

---

plugins/module_utils/network/sonic/config/lag_interfaces/lag_interfaces.py

I deleted the portchannel name split in config to accommodate changed behavior.
lag_interfaces
[regression-2022-09-27-16-19-55.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9660232/regression-2022-09-27-16-19-55.html.pdf)
[lag_interfaces_output.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9660234/lag_interfaces_output.log)

Deleted port name split for lag_interfaces

---

plugins/module_utils/network/sonic/argspec/ntp/ntp.py
plugins/module_utils/network/sonic/config/ntp/ntp.py
plugins/module_utils/network/sonic/facts/ntp/ntp.py
plugins/modules/sonic_ntp.py
tests/regression/roles/sonic_ntp/defaults/main.yml

SUMMARY
This is to add NTP server "prefer" attribute to NTP module.
ISSUE TYPE
- Module Enhancement Pull Request
COMPONENT NAME
sonic_ntp
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9767805/regression_test.log)
[regression-2022-10-12-10-50-29.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9767807/regression-2022-10-12-10-50-29.html.pdf)

Add server "prefer" attribute to NTP module

---

plugins/module_utils/network/sonic/facts/l2_interfaces/l2_interfaces.py

The l2_interface "facts" facility previously accepted only the "-" character/string as a vlan "range" delimiter for specifying allowed trunking vlans to be configured on an interface. Recent SONiC images have modified the implementation to use the OC Yang compliant ".." string instead. (e.g. The range previously specified as "5-7" is now specified as "5..7".)
This change set provides a modified, backward compatible implementation for l2_interface "facts" gathering by allowing and handling either of these options for the vlan trunking allowed range string delimiter.
l2_interfaces
Regression Test Results:
[l2_interfaces_facts_vlan_range_string_change_html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9762084/l2_interfaces_facts_vlan_range_st …

Allow use of the OC Yang compliant vlan range delimiter ".." in new SONiC images

---

.github/workflows/ansible-test.yml

The Ansible core team has announced that the Ansible core "2.14" version is stable and should be added to collection workflow test matrices.
This PR is to add it to the Dell enterprise_sonic test matrix.
Add "stable-2.14" to the test matrix for the sonic_enterprise collection in the .github workflows "ansible-test.yml" file .
workflows
```paste below
```

Add "stable-2.14" to our test matrix

---

tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml

I updated the test cases to reflect cvl neighbor validation code changes.
sonic(config-router-bgp-neighbor)# peer-group PG1
sonic(config-router-bgp-neighbor)# peer-group PG2
%Error: Cannot change the peer-group. Deconfigure first
sonic_bgp_neighbors
[regression-2022-10-24-10-28-10.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9853982/regression-2022-10-24-10-28-10.html.pdf)

Updated test cases to reflect cvl neighbor validation code changes.

---

plugins/module_utils/network/sonic/argspec/ntp/ntp.py
plugins/module_utils/network/sonic/config/ntp/ntp.py
plugins/modules/sonic_ntp.py

SUMMARY
Make NTP server minpoll and maxpoll attributes be configured together. This is required by SONIC.
ISSUE TYPE
COMPONENT NAME
sonic_ntp
[regression-2022-10-28-09-58-25.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9890701/regression-2022-10-28-09-58-25.html.pdf)
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/9890703/regression_test.log)
```

Make NTP minpoll and maxpoll config together

---

playbooks/common_examples/mgmt_vrf_config.yaml
playbooks/common_examples/mgmt_vrf_off.yaml
playbooks/common_examples/mgmt_vrf_on.yaml

I added tasks for configuring and unconfiguring the mgmt vrf as a workaround for the mgmt vrf vug.
sonic_vrfs
[mgmt_vrf_config_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10239729/mgmt_vrf_config_output.txt)

Provided workaround for SONiC mgmt vrf bug

---

plugins/module_utils/network/sonic/argspec/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/sonic/config/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/sonic/facts/l2_interfaces/l2_interfaces.py
plugins/modules/sonic_l2_interfaces.py
tests/regression/roles/sonic_l2_interfaces/defaults/main.yml

- Change the argspec to use a string instead of an integer when specifying a vlan or a vlan range.
- Add handling to support a "vlan" argument that specifies a vlan range in the form "X-Y".
- provide correct tracking of commands sent to the device after eliminating requested configuration that is already present on the device.
- Fix bugs causing incorrect reporting of the original playbook command "invocation" and the final set of commands sent to the device.
- Add regression test cases to cover the possible overlap conditions between trunk vlans and ranges configured on the device and requested additions or deletions of trunk vlans and ranges.
sonic_l2_interfaces
Regression test results:
[vlan_range_feature_regression_report_with_sanity_fixes_2023-01-06-13-54-12_htm …

playbook support for vlan trunk ranges

---

plugins/module_utils/network/sonic/argspec/mclag/mclag.py
plugins/module_utils/network/sonic/config/mclag/mclag.py
plugins/module_utils/network/sonic/facts/mclag/mclag.py
plugins/modules/sonic_mclag.py
tests/regression/roles/sonic_mclag/defaults/main.yml
tests/regression/roles/sonic_mclag/tasks/cleanup_tests.yaml
tests/regression/roles/sonic_mclag/tasks/main.yml

Add below attributes to MCLAG resource model
- delay_restore
- gateway_mac
- peer_gateway
sonic_mclag
- Regression test HTML report:
[mclag_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10175167/mclag_regression_report.pdf)
- Regression test detailed log:
[sonic_mclag_regression_terminal_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10175176/sonic_mclag_regression_terminal_output.txt)
- Running config and respective facts gathered:
[show_running_get_facts_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10175181/show_running_get_facts_output.txt)

Add new attributes to MCLAG resource model

---

plugins/module_utils/network/sonic/argspec/ntp/ntp.py
plugins/module_utils/network/sonic/config/ntp/ntp.py
plugins/module_utils/network/sonic/facts/ntp/ntp.py
plugins/module_utils/network/sonic/utils/utils.py
plugins/modules/sonic_ntp.py
tests/regression/roles/sonic_ntp/defaults/main.yml

SUMMARY
This to add replaced and overridden states to NTP module.
ISSUE TYPE
COMPONENT NAME
sonic_ntp
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10493394/regression_test.log)
[regression-2023-01-24-09-39-43.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10493397/regression-2023-01-24-09-39-43.html.pdf)

Add NTP replaced and overridden states to NTP module

---

plugins/module_utils/network/sonic/argspec/vrfs/vrfs.py
plugins/module_utils/network/sonic/config/vrfs/vrfs.py
plugins/module_utils/network/sonic/utils/utils.py
plugins/modules/sonic_vrfs.py
tests/regression/roles/sonic_vrfs/defaults/main.yml

SUMMARY
This is to add support for replaced and overridden states to VRFS module.
ISSUE TYPE
COMPONENT NAME
soniuc_vrfs
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10668193/regression_test.log)
[regression-2023-02-03-11-41-35.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10668199/regression-2023-02-03-11-41-35.html.pdf)

Add replaced and overridden states support to VRFS module

---

plugins/module_utils/network/sonic/argspec/system/system.py
plugins/module_utils/network/sonic/config/system/system.py
plugins/module_utils/network/sonic/utils/utils.py
plugins/modules/sonic_system.py
tests/regression/roles/sonic_system/defaults/main.yml

SUMMARY
This is to add "replaced" and "overridden" states to sonic_system module.
ISSUE TYPE
COMPONENT NAME
sonic_system
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10709943/regression_test.log)
[regression-2023-02-10-08-43-14.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10709946/regression-2023-02-10-08-43-14.html.pdf)

Add replaced and overridden to System module

---

docs/SUPPORT.md

This PR has been raised, as the original [PR#143](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/143) was closed due to deletion of head repository.
Have mentioned the comments below given in previous PR and its response.
<strong>jeff-yin  : Line 15 : </strong>I don't think we should use e-mail to provide/receive feedback. If folks have feedback they should just open an issue. The development team is subscribed to the repositories so we will get notified via e-mail anyway.
<strong>KVSK </strong> addressed.
<strong>jeff-yin  : Line 14 : </strong>Why don't we link this repo directly? i.e., https://github.com/ansible-collections/dellemc.enterprise_sonic/issues
<strong>KVSK</strong> addressed.
<strong>jeff-yin : Line 13: </strong> Why don't we link to this repo directly? …

Support template under docs folder

---

plugins/module_utils/network/sonic/utils/utils.py

Ansible recently merged changes in the Ansible Netcommon repo that eliminated the source functions for several utilities imported into modules in the enterprise_sonic collection. The affected utility functions are available in the ansible/ansible (library) repo and have been there since the earliest Ansible core version that is currently supported. Because of this, the source of the imports can be changed in the enterprise_sonic collection without introducing any downward compatibility problems.
This change modifies the enterprise_sonic **utils** module to move the import source for the **is_masklen** and **to_netmask** utility functions from
ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
to
ansible.module_utils.common.network
REF: Ansible Netcommon …

Fix sanity errors caused by deletion of Ansible Netcommon utilities

---

.github/workflows/ansible-test.yml
tests/unit/compat/mock.py
tests/unit/compat/unittest.py
tests/unit/modules/conftest.py
tests/unit/modules/network/sonic/fixtures/sonic_dhcp_relay.yaml
tests/unit/modules/network/sonic/sonic_module.py
tests/unit/modules/network/sonic/test_sonic_dhcp_relay.py
tests/unit/modules/utils.py

- Add common unit test module with mock functions for Enterprise SONiC ansible resource modules.
- Add unit tests for 'dhcp_relay' resource module.
- Update github workflow to run unit tests with ansible-test and generate code coverage.
- Unit tests
- dhcp_relay
Unit test logs and coverage report - [ansible_test_units_coverage_logs.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10352196/ansible_test_units_coverage_logs.txt)

Add common unit test module and 'dhcp_relay' resource module unit tests

---

tests/unit/compat/mock.py

For pylint, disable unused-import in compat/mock.py to avoid pylint failure for imports not used directly within that file.
- unit test

[unit test] pylint disable unused-import in compat/mock.py

---

.github/workflows/code-coverage.yml

Install released version of dependencies from ansible galaxy in code coverage workflow, instead of installing directly from git.
- workflow

Install dependencies from ansible galaxy in code coverage workflow

---

tests/unit/modules/network/sonic/fixtures/sonic_prefix_lists.yaml
tests/unit/modules/network/sonic/test_sonic_prefix_lists.py

Unit testing code for prefix_list module added
prefix_list unit testing

prefix_list unit testing code added

---

tests/unit/modules/network/sonic/fixtures/sonic_ip_neighbor.yaml
tests/unit/modules/network/sonic/test_sonic_ip_neighbor.py

Unit testing for ip_neighbor module added
ip_neighbor Unit Testing

Unit testing for ip_neighbor module added

---

tests/unit/modules/network/sonic/fixtures/sonic_facts.yaml
tests/unit/modules/network/sonic/test_sonic_facts.py

Unit testing code for modules/sonic_facts.py added
sonic_facts Unit Testing
The main objective of UT is to ensure that all files present in plugins/modules folder are covered. This particular file sonic_facts.py is a common module to pull out the facts for all other modules.
This file is not specific to any particular protocol and hence the unit test cases for this file does not follow the same strategy as the protocol unit testing code. This unit testing is only to ensure that the code coverage for this file is met.
The actual functionality for each protocol is being validated in the unit testing that corresponds to the protocol unit testing code. 
The strategy used in this proposed change is to call any one protocol facts code and test the same using stub return …

Unit testing code for modules/sonic_facts.py added

---

plugins/module_utils/network/sonic/config/bfd/bfd.py
plugins/module_utils/network/sonic/config/copp/copp.py

I removed repetitive get diff call in replaced for bfd and copp modules.
sonic_bfd
sonic_copp
[regression-2023-05-03-11-35-12.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11389957/regression-2023-05-03-11-35-12.html.pdf)

Removed repetitive get_diff call in replace function

---

tests/regression/roles/sonic_vrfs/templates/cli_test_case_01.cfg

I removed the space between the PortChannel and ID that was causing the CLI test case to fail
sonic_vrfs
[regression-2023-05-09-13-08-56.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11435751/regression-2023-05-09-13-08-56.html.pdf)

Fixed failing CLI test case for vrfs module

---

changelogs/fragments/257-vrfs-cli-test-case-fix.yaml
changelogs/fragments/260-interfaces-timeout-fix.yaml
tests/regression/roles/sonic_interfaces/tasks/tasks_template.yaml

Increased the command timeout in the task template for the interfaces test cases.
[regression-2023-05-11-14-09-50.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11456500/regression-2023-05-11-14-09-50.html.pdf)

Increased command timeout for interfaces test cases

---

changelogs/fragments/250-bgp-as-paths-fix-merged-deleted.yaml
plugins/module_utils/network/sonic/config/bgp_as_paths/bgp_as_paths.py
plugins/module_utils/network/sonic/facts/bgp_as_paths/bgp_as_paths.py
plugins/modules/sonic_bgp_as_paths.py
tests/regression/roles/sonic_bgp_as_paths/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_bgp_as_paths.yaml

Incorporate the below fixes in bgp_as_paths:
- In merged, do not overwrite the action of an existing as-path-list.
- In deleted, delete the as-path-list if all members in it are to be deleted.
|  N/A |
- sonic_bgp_as_paths
- Regression test HTML report:
[bgp_as_paths _regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11354338/bgp_as_paths._regression_report.pdf)
- Regression test detailed log:
[bgp_as_paths_regression_terminal_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11354333/bgp_as_paths_regression_terminal_output.txt)

bgp_as_paths - Fix issues in merged and deleted states

---

changelogs/fragments/248-dhcp-relay-replaced-overridden-support.yaml
changelogs/fragments/249-dhcp-relay-replaced-overridden-support.yaml
plugins/module_utils/network/sonic/argspec/dhcp_relay/dhcp_relay.py
plugins/module_utils/network/sonic/config/dhcp_relay/dhcp_relay.py
plugins/module_utils/network/sonic/facts/dhcp_relay/dhcp_relay.py
plugins/modules/sonic_dhcp_relay.py
tests/regression/roles/sonic_dhcp_relay/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_dhcp_relay.yaml
tests/unit/modules/network/sonic/test_sonic_dhcp_relay.py

- Add support for replaced, overridden states in `dhcp_relay` module.
- Add regression and unit test cases to cover replaced and overridden states.
| N/A  |
- sonic_dhcp_relay
- Regression test HTML report:
[dhcp_relay_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11344375/dhcp_relay_regression_report.pdf)
- Regression test detailed log:
[dhcp_relay_regression_terminal_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11344379/dhcp_relay_regression_terminal_output.txt)

dhcp_relay - Add support for 'replaced' and 'overridden' states

---

plugins/module_utils/network/sonic/argspec/tacacs_server/tacacs_server.py
plugins/module_utils/network/sonic/config/tacacs_server/tacacs_server.py
plugins/modules/sonic_tacacs_server.py
tests/regression/roles/sonic_tacacs_server/defaults/main.yml

SUMMARY
This is to add "replaced" and "overridden" states support for sonic_tacacs_server resource module.
GitHub Issues
"N/A".
ISSUE TYPE
COMPONENT NAME
sonic_tacacs_server
OUTPUT
[regression-2023-04-13-10-48-02.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11236497/regression-2023-04-13-10-48-02.html.pdf)
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11236498/regression_test.log)
[unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11236501/unit_test.log)
[tacacs.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11236503/tacacs.txt) …

Add replaced and overridden states support for TACACS server resource module

---

plugins/module_utils/network/sonic/argspec/radius_server/radius_server.py
plugins/module_utils/network/sonic/config/radius_server/radius_server.py
plugins/module_utils/network/sonic/facts/radius_server/radius_server.py
plugins/modules/sonic_radius_server.py
tests/regression/roles/sonic_radius_server/defaults/main.yml

SUMMARY
This is to add "replaced" and "overridden" states support for sonic_radius_server resource module.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_radius_server
OUTPUT
[regression-2023-04-18-10-08-35.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11275185/regression-2023-04-18-10-08-35.html.pdf)
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11275187/regression_test.log)
[radius.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11275193/radius.txt)
[unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11275198/unit_test.log)
Checklist: …

Add replaced and overridden states support for sonic_radius_server module

---

changelogs/fragments/276-add-new-port-breakout-modes.yaml
plugins/module_utils/network/sonic/argspec/port_breakout/port_breakout.py
plugins/module_utils/network/sonic/utils/utils.py
plugins/modules/sonic_port_breakout.py
tests/regression/roles/sonic_port_breakout/defaults/main.yml
tests/regression/roles/sonic_port_breakout/tasks/main.yml
tests/regression/roles/sonic_port_breakout/tasks/tasks_template.yaml
tests/regression/roles/sonic_port_breakout/templates/cli_test_case_01.cfg

Add Ansible support for all port breakout modes currently supported by SONiC
- Add support for all currently supported port breakout modes.
- Fix deficiencies and duplication in test case definitions for the port_breakout resource module.
- Add a 10 second pause between test sections to avoid SONiC errors due to back-to-back
port breakout configuration commands.
- Reorder breakout modes in the argspec and module files to facilitate verification of the list of supported modes.
- Use an algorithm instead of a map to obtain the openconfig "speed" value to be set for each specified breakout mode. This eliminates the need to manually add a map entry when adding support for a new breakout mode.
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this …

Add Ansible support for all port breakout modes currently supported by SONiC

---

changelogs/fragments/277-enable-running-all-regression-tests-on-s5296.yaml
tests/regression/roles/common/defaults/main.yml
tests/regression/roles/sonic_interfaces/defaults/main.yml
tests/regression/roles/sonic_l3_interfaces/defaults/main.yml

Enable contiguous execution of all regression integration tests on an S5296f.
- Modify/add interface names to avoid port group interfaces for the "interfaces" test.
- Remove "interfaces" and "l3_interfaces" test cases that delete all interface configuration to prevent disabling the Management 0 interface connection.
These changes are a prerequisite for enabling automated regression test execution.
| |
N/A
regression_tests
[s5296f_all_resource_modules_regression.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11887943/s5296f_all_resource_modules_regression.pdf)
```paste below
```
Please describe …

Enable contiguous execution of all regression integration tests on an S5296f.

---

changelogs/fragments/279-playbook-check-diff-modes-and-radius-server-implement.yaml
plugins/module_utils/network/sonic/config/radius_server/radius_server.py
plugins/module_utils/network/sonic/utils/formatted_diff_utils.py
plugins/module_utils/network/sonic/utils/utils.py

SUMMARY
This is to add playbook check and diff modes utility functions and radius-server support for check and diff modes.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_radius_server
OUTPUT
- test script: 
[radius.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11984116/radius.txt)
- test log with --diff option: 
[ut_diff.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12030189/ut_diff.log)
- test log with --diff and --check: 
[ut_diff_check.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12030193/ut_diff_check.log)
[regression.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12022305/regression.log)
- regression test result: …

Playbook check and diff modes util and radius-server implemetation

---

.github/workflows/ansible-test.yml
changelogs/fragments/282-update-changelog-workflow.yaml

Change trigger of changelog workflow to run only for PRs and skip for push events.
|  N/A |
- workflow

[workflow] Change trigger of changelog workflow to run only for PRs

---

changelogs/fragments/282-bgp-cli-auto-regression-fix.yaml
changelogs/fragments/283-bgp-cli-auto-regression-fix.yaml
tests/regression/roles/sonic_bgp/tasks/main.yml

Fix the bgp CLI test base_cfg_path derivation of the bgp role_path by avoiding relative pathing from the possibly external playbook_dir.
Explanation: The automated regression test infrastructure runs the regression suite using a top level playbook file that is located outside of the repo being tested. This is valid. The failure seen with the regression suite in the bgp resource module "CLI" test was caused by the fact that the path to the bgp resource module regression test "role" was derived in the bgp regression test "main" task using an assumed relative path from the playbook instead of explicitly using the known path to the role.
| |
N/A …

Fix the bgp CLI automated regression test external playbook failure 

---

changelogs/fragments/281-playbook-check-diff-modes-for-ntp-module.yaml
plugins/module_utils/network/sonic/config/ntp/ntp.py
plugins/module_utils/network/sonic/config/radius_server/radius_server.py
plugins/module_utils/network/sonic/config/tacacs_server/tacacs_server.py
plugins/module_utils/network/sonic/utils/formatted_diff_utils.py

SUMMARY
- add diff and check modes support for NTP and TACACS modules.
- add some change on get_new_config utility functions.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_ntp, sonic_tacacs_server
OUTPUT
- NTP regression test log: 
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12088333/regression_test.log)
- NTP regression test result: 
[regression-2023-07-18-10-46-56.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12088336/regression-2023-07-18-10-46-56.html.pdf)
- NTP unit test script:
[ntp.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12088337/ntp.txt)
- NTP unit test with --diff option log:
[ut_diff.log](https://github.com/ansible-collections/dellemc.ent …

Add diff and check modes support for NTP module

---

changelogs/fragments/285-playbook-check-diff-modes-for-vrfs-logging-ip-neighbor.yaml
plugins/module_utils/network/sonic/config/ip_neighbor/ip_neighbor.py
plugins/module_utils/network/sonic/config/logging/logging.py
plugins/module_utils/network/sonic/config/vrfs/vrfs.py

SUMMARY
This is to add diff and check modes supports for ip_neigbor, vrfs and logging modules.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_vrfs, sonic_ip_neighbor, sonic_logging
OUTPUT
- ip_neighbor regression result:
[ip_regression-2023-08-07-09-19-08.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12283155/ip_regression-2023-08-07-09-19-08.html.pdf)
- ip_neigbor: unit test script:
[ip_neighbor.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12283159/ip_neighbor.txt)
- ip_neighbor unit test with --diff option:
[ip_log_diff.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12283162/ip_log_diff.log)
- ip_neighbor unit test with --diff and --check options: …

Add diff check modes support for vrfs logging and ip_neighbor modules

---

changelogs/fragments/293-add-mgmt-vrf-handling-in-vrfs-module.yaml
plugins/module_utils/network/sonic/config/vrfs/vrfs.py
tests/unit/modules/network/sonic/fixtures/sonic_vrfs.yaml

SUMMARY
This is to add mgmt VRF handling to sonic_vrfs module
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_vrfs
OUTPUT
- regression test result:
[regression-2023-09-08-09-42-24.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12562997/regression-2023-09-08-09-42-24.html.pdf)
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12563000/regression_test.log)
[unit_test_script.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12479993/unit_test_script.txt)
[unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12479994/unit_test.log)
mgmt VRF handling in …

Add mgmt VRF handling to VRFS module

---

changelogs/fragments/291-port-breakout-replaced-overridden-support.yaml
plugins/module_utils/network/sonic/argspec/port_breakout/port_breakout.py
plugins/module_utils/network/sonic/config/port_breakout/port_breakout.py
plugins/modules/sonic_port_breakout.py
tests/regression/roles/sonic_port_breakout/defaults/main.yml
tests/regression/roles/sonic_port_breakout/tasks/tasks_template.yaml
tests/unit/modules/network/sonic/fixtures/sonic_port_breakout.yaml
tests/unit/modules/network/sonic/test_sonic_port_breakout.py

- Add support for replaced, overridden states in `port_breakout` module.
- Add regression test cases to cover replaced and overridden states.
- Updated documentation examples.
|  N/A |
- sonic_port_breakout
- Regression test HTML report: [port_breakout_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12416186/port_breakout_regression_report.pdf)
- Regression test detailed log: [port_breakout_regression_terminal_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12416191/port_breakout_regression_terminal_output.txt)

port_breakout - Add support for 'replaced' and 'overridden' states

---

changelogs/fragments/290-bgp-as-paths-replaced-overridden-support.yaml
plugins/module_utils/network/sonic/argspec/bgp_as_paths/bgp_as_paths.py
plugins/module_utils/network/sonic/config/bgp_as_paths/bgp_as_paths.py
plugins/modules/sonic_bgp_as_paths.py
tests/regression/roles/sonic_bgp_as_paths/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_bgp_as_paths.yaml
tests/unit/modules/network/sonic/test_sonic_bgp_as_paths.py

- Add support for replaced, overridden states in `bgp_as_paths` module.
- Add regression test cases to cover replaced and overridden states.
|  N/A |
- sonic_bgp_as_paths
- Regression test HTML report: [bgp_as_paths_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12407059/bgp_as_paths_regression_report.pdf)
- Regression test detailed log: [bgp_as_paths_regression_terminal_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12407065/bgp_as_paths_regression_terminal_output.txt)

bgp_as_paths - Add support for 'replaced' and 'overridden' states

---

changelogs/fragments/289-bgp-neighbors-prefix-limit-fix.yaml
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/bgp_neighbors_af/bgp_neighbors_af.py
plugins/module_utils/network/sonic/facts/bgp_neighbors_af/bgp_neighbors_af.py
plugins/module_utils/network/sonic/utils/bgp_utils.py
plugins/modules/sonic_bgp_neighbors.py
plugins/modules/sonic_bgp_neighbors_af.py
tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml
tests/regression/roles/sonic_bgp_neighbors_af/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_bgp_neighbors_af.yaml

SONiC code no longer supports prefix-limit configuration for l2vpn evpn. I updated module code and test cases to reflect this.
sonic_bgp_neighbors
sonic_bgp_neighbors_af
[regression-2023-08-21-10-39-08.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12399348/regression-2023-08-21-10-39-08.html.pdf)
[regression-2023-08-21-11-39-02.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12399686/regression-2023-08-21-11-39-02.html.pdf)
[prefix_limit_test_case_err_msg.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12399700/prefix_limit_test_case_err_msg.txt)

Fixed BGP neighbors prefix-limit bug

---

changelogs/fragments/303-playbook-check-diff-modes-for-l2-lag-interfaces.yaml
plugins/module_utils/network/sonic/config/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/sonic/config/lag_interfaces/lag_interfaces.py
tests/sanity/ignore-2.17.txt

SUMMARY
This is to add check and diff modes support for l2-interfaces and lag-interfaces modules.
GitHub Issues
N/A
ISSUE TYPE
- 
COMPONENT NAME
sonic_l2_interfaces, sonic_lag_interfaces
OUTPUT
- l2_interfaces regression result: 
[l2_interfaces_regression-2023-10-13-11-55-14.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12898850/l2_interfaces_regression-2023-10-13-11-55-14.html.pdf)
- l2_interfaces regression log: 
[l2_interfaces_regression.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12898853/l2_interfaces_regression.log)
- l2_interfaces unit test script: 
[l2_interfaces.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12898862/l2_interfaces.txt)
- l2_interfaces unit test log: …

Check and diff modes support for l2- and lag-interfaces modules

---

changelogs/fragments/284-playbook-check-diff-modes-for-system-and-port-group-modules.yaml
plugins/module_utils/network/sonic/config/port_group/port_group.py
plugins/module_utils/network/sonic/config/system/system.py

SUMMARY
This is to add check and diff modes support for system and port-group modules.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_system, sonic_port_group
OUTPUT
- system regression result: 
[system_regression-2023-08-02-09-29-53.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12242936/system_regression-2023-08-02-09-29-53.html.pdf)
- system unit test script: 
[system.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12242951/system.txt)
- system unit test log with --diff option: 
[sys_log_diff.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12242952/sys_log_diff.log)
- system unit test with --diff and --check options: …

Add check and diff modes support for system and port group modules

---

changelogs/fragments/304-playbook-check-diff-modes-for-users-aaa.yaml
plugins/module_utils/network/sonic/config/aaa/aaa.py
plugins/module_utils/network/sonic/config/users/users.py
plugins/modules/sonic_aaa.py
plugins/modules/sonic_users.py

SUMMARY
This is to add diff and check modes supports for users and aaa resource modules.
GitHub Issues
N/A
ISSUE TYPE
COMPONENT NAME
sonic_users, sonic_aaa
OUTPUT
- users regression test result: 
[users_regression-2023-10-19-09-42-50.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13073915/users_regression-2023-10-19-09-42-50.html.pdf)
- users regression test log: 
[users_regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13073917/users_regression_test.log)
- users unit test script: 
[users.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13073919/users.txt)
- users unit test log: 
[users_unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/file …

users and aaa module diff and check modes

---

changelogs/fragments/318-playbook-diff-mode-enhancement.yaml
plugins/module_utils/network/sonic/config/aaa/aaa.py
plugins/module_utils/network/sonic/config/acl_interfaces/acl_interfaces.py
plugins/module_utils/network/sonic/config/interfaces/interfaces.py
plugins/module_utils/network/sonic/config/ip_neighbor/ip_neighbor.py
plugins/module_utils/network/sonic/config/l2_acls/l2_acls.py
plugins/module_utils/network/sonic/config/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/sonic/config/l3_acls/l3_acls.py
plugins/module_utils/network/sonic/config/lag_interfaces/lag_interfaces.py
plugins/module_utils/network/sonic/config/logging/logging.py
plugins/module_utils/network/sonic/config/ntp/ntp.py
plugins/module_utils/network/sonic/config/port_group/port_group.py
plugins/module_utils/network/sonic/config/radius_server/radius_server.py
plugins/module_utils/network/sonic/config/static_routes/static_routes.py
plugins/module_utils/network/sonic/config/system/system.py
plugins/module_utils/network/sonic/config/tacacs_server/tacacs_server.py
plugins/module_utils/network/sonic/config/users/users.py
plugins/module_utils/network/sonic/config/vlans/vlans.py
plugins/module_utils/network/sonic/config/vrfs/vrfs.py
plugins/module_utils/network/sonic/utils/formatted_diff_utils.py
plugins/modules/sonic_ip_neighbor.py
plugins/modules/sonic_logging.py
plugins/modules/sonic_ntp.py
plugins/modules/sonic_port_group.py

- Enhance config generation utility to allow plugin for "merged" state handling.
- Change config diff utility to use json_dump instead of pformat, and generate console output for diff strings.
- Change module result with "diff" attribute instead of "config_diff"
N/A
All modules which have invoked "get_formatted_config_diff" util function.
Take sonic_radius_server as sample (All regression tests and all unit tests results and logs are too many to be attached.  If needed, please ask and will be provided):
[radius.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13729181/radius.txt)
- log for playbook with --diff: 
[radius_diff.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13729192/radius_diff.l …

Change config diff utility function

---

changelogs/fragments/319-bgp-communities-no-member-facts-fix.yaml
plugins/module_utils/network/sonic/facts/bgp_communities/bgp_communities.py
tests/regression/roles/sonic_bgp_communities/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_bgp_communities.yaml

The change set merged for PR #251 (bgp_communities - Add support for replaced and overridden states: https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/251) introduced a crash exposure in the "facts" file for the case in which a configured BGP community list exists, but has no members. If this configuration case exists, any attempt to gather Ansible "facts" for the bgp_communities resource module fails with a crash during parsing of the configuration for the BGP community list with the empty member list. As a result, all playbook tasks fail for this resource module.
The crash occurs due to an attempt to access a non-existent "type" element of the "result" dict for the current BGP Community list to determine how to parse the "member" attributes. (No value was being set …

Fix bgp_communities facts handling for empty member lists.

---

changelogs/fragments/329-regression-test-automated-intf-naming-config.yaml
tests/regression/roles/sonic_route_maps/defaults/main.yml
tests/regression/test.yaml

This change set is proposed to facilitate automated testing runs for both interface-naming modes: "native" and "standard". It contains the following fixes:
1) It provides a simple change to automatically cause the configuration of the target switch interface-naming mode to match the interface-naming mode selected for the test run. This is accomplished by moving the "system" resource module integration test to the beginning of the module test list. Because the "system" resource module integration test does a cleanup task that configures the switch with the selected interface-naming mode specified in the test "defaults" file (tests/regression/roles/common/defaults/main.yaml), placing this test first in the list of tests to be run causes the matching interface-naming mode to be present for …

Configure the selected interface naming test mode at the start of a regression run.

---

changelogs/fragments/328-playbook-check-diff-modes-for-l3-interfaces.yaml
plugins/module_utils/network/sonic/config/l3_interfaces/l3_interfaces.py
plugins/module_utils/network/sonic/utils/formatted_diff_utils.py
plugins/modules/sonic_l3_interfaces.py

This is to add diff and check modes support for l3_interfaces resource module.
N/A
sonic_l3_interfaces
[regression-2024-01-19-12-21-34.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13994359/regression-2024-01-19-12-21-34.html.pdf)
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13994362/regression_test.log)
[l3_interfaces.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13994369/l3_interfaces.txt)
[unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13994374/unit_test.log)
Run regression test and lots of unit tests

Add diff and check for l3_interfaces module

---

changelogs/fragments/330-add-external-ip-attribute-for-vxlan.yaml
plugins/module_utils/network/sonic/argspec/vxlans/vxlans.py
plugins/module_utils/network/sonic/config/vxlans/vxlans.py
plugins/module_utils/network/sonic/facts/vxlans/vxlans.py
plugins/modules/sonic_vxlans.py
tests/regression/roles/sonic_vxlan/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_vxlans.yaml

adding support to retrieve and configure external ip attribute in vxlan resource module to match the CLI.
|#327 |
sonic_vxlan
[vxlan_regression_output1-24-24.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14057553/vxlan_regression_output1-24-24.txt)
[vxlan_regression_results_pdf1-24-24.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14057554/vxlan_regression_results_pdf1-24-24.pdf)
none
added attribute to existing tests

Vxlan external ip feature

---

tests/regression/roles/sonic_dhcp_snooping/defaults/main.yml

Fix dhcp_snooping regression failure.
sonic_dhcp_snooping
- regression result:
[regression-2024-02-26-17-39-33.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14408411/regression-2024-02-26-17-39-33.html.pdf)
- regression log: 
[regression.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14408412/regression.log)
Run regression testing

Fix dhcp_snooping regression failure

---

changelogs/fragments/346-playbook-check-diff-modes-for-bfd-copp-dhcps.yaml
plugins/module_utils/network/sonic/config/bfd/bfd.py
plugins/module_utils/network/sonic/config/copp/copp.py
plugins/module_utils/network/sonic/config/dhcp_relay/dhcp_relay.py
plugins/module_utils/network/sonic/config/dhcp_snooping/dhcp_snooping.py
plugins/module_utils/network/sonic/utils/formatted_diff_utils.py
plugins/modules/sonic_bfd.py
plugins/modules/sonic_copp.py
plugins/modules/sonic_dhcp_relay.py
plugins/modules/sonic_dhcp_snooping.py

Th is to add diff and check modes support for copp, bfd, dhcp_relay and dhcp_snooping modules.
N/A
sonic_bfd, sonic_copp, sonic_dhcp_relay, sonic_dhcp_snooping
- bfd_regression result: 
[bfd_regression-2024-02-23-00-22-13.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14409158/bfd_regression-2024-02-23-00-22-13.html.pdf)
- bfd regression log: 
[bfd_regression.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14409160/bfd_regression.log)
- bfd unit test log: 
[bfd_unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14409162/bfd_unit_test.log)
- bfd unit test script: 
[bfd_unit_test.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14409167/bfd_unit_test. …

bfd, copp and dhcp relay and snooping check and diff modes

---

tests/regression/roles/sonic_port_group/defaults/main.yml

Fix port_group regression failure.
It is due to a restriction in the latest Ansible version from tighter enforcement of the argspec.
N/A
sonic_port_group
- [regression-2024-03-15-16-25-30.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14618302/regression-2024-03-15-16-25-30.html.pdf)
- [regression.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14618305/regression.log)
Run regression test.

Fix port_group regression failure

---

changelogs/fragments/317-added-protocol-option-for-syslog-module.yaml
plugins/module_utils/network/sonic/argspec/logging/logging.py
plugins/module_utils/network/sonic/config/logging/logging.py
plugins/module_utils/network/sonic/facts/logging/logging.py
plugins/modules/sonic_logging.py
tests/regression/roles/sonic_logging/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_logging.yaml

Addition of protocol option in syslog server.
| | N/A
logging
**Regression report:**
[regression_report_logging.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13672599/regression_report_logging.pdf)
**Sanity test:**
[sanity test.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13672048/sanity.test.txt)
**show logging server CLI and its related facts:**
[facts_UT.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13672197/facts_UT.txt)
**Checklist:**
**How Has This Been Tested?**
Run sanity, regression and unit tests.

Add protocol option in syslog server

---

changelogs/fragments/366-github-issue-357-fix.yaml
plugins/module_utils/network/sonic/config/interfaces/interfaces.py
tests/sanity/ignore-2.18.txt
tests/sanity/ignore-3.10.txt
tests/sanity/ignore-3.11.txt
tests/sanity/ignore-3.12.txt
tests/unit/modules/network/sonic/fixtures/sonic_interfaces.yaml

- fix GitHub issue#357
- fix the issue with deleted handling
- fix some other issues.
When "overridden", The "enabled" is not set to its default value.
GitHub Issue #
#357
[regression-2024-04-08-21-10-42.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14921245/regression-2024-04-08-21-10-42.html.pdf)
[Uploading regression.log…]()
[unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/14921249/unit_test.log)
Run regression test and unit tests.

Fix GitHub issue#357 and more issues

---

changelogs/fragments/381-fix-copp-states.yaml
plugins/module_utils/network/sonic/config/copp/copp.py
plugins/module_utils/network/sonic/facts/copp/copp.py
plugins/modules/sonic_copp.py
tests/unit/modules/network/sonic/fixtures/sonic_copp.yaml
tests/unit/modules/network/sonic/test_sonic_copp.py

- Fixed the state implementation bugs in the config file and made minor updates to other files
sonic_copp
[regression-2024-06-06-13-52-06.html.pdf](https://github.com/user-attachments/files/15686355/regression-2024-06-06-13-52-06.html.pdf)
[diff_output.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/15280811/diff_output.log)

Fixed CoPP module states implementation bug

---

tests/regression/roles/sonic_stp/defaults/main.yml

This is to fix stp module regression failures. SONIC changes causes the failures: in mst mode, no vlan disable allowed.
N/A
sonic_stp
[regression-2024-06-06-18-37-39.html.pdf](https://github.com/user-attachments/files/15686524/regression-2024-06-06-18-37-39.html.pdf)
Run regression testing.

stp regression failures fix

---

changelogs/fragments/396-port-group-facts-enhancement.yaml
plugins/module_utils/network/sonic/facts/port_group/port_group.py

I made the error message for port group facts gathering more descriptive to accommodate platforms that don't support the feature.
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".\
| #387 |
sonic_port_group
[facts_gathering.log](https://github.com/user-attachments/files/15811104/facts_gathering.log)
[regression-2024-06-12-15-13-17.html.pdf](https://github.com/user-attachments/files/15811445/regression-2024-06-12-15-13-17.html.pdf)

Make error message for port group facts gathering more descriptive

---

changelogs/fragments/395-comment-out-pfc-pg-test-cases.yaml
plugins/module_utils/network/sonic/facts/qos_maps/qos_maps.py
tests/regression/roles/sonic_qos_maps/defaults/main.yml

I commented out PFC priority group map test case configuration since the configuration is only supported on certain platforms.
sonic_qos_maps
[regression-2024-06-11-10-14-49.html.pdf](https://github.com/user-attachments/files/15792799/regression-2024-06-11-10-14-49.html.pdf)

Comment out PFC priority group map test case configuration

---

tests/regression/roles/sonic_aaa/defaults/main.yml

I commented out AAA regression test case 2 because such configuration will cause a lockout on the switch during regression execution.
sonic_aaa
[regression-2024-06-26-12-39-57.html.pdf](https://github.com/user-attachments/files/15994551/regression-2024-06-26-12-39-57.html.pdf)

Update AAA regression test cases for 2.5.0

---

changelogs/fragments/413-route-maps-set-tag-support-and-doc-updates.yaml
plugins/module_utils/network/sonic/argspec/route_maps/route_maps.py
plugins/module_utils/network/sonic/config/route_maps/route_maps.py
plugins/module_utils/network/sonic/facts/route_maps/route_maps.py
plugins/modules/sonic_route_maps.py
tests/regression/roles/sonic_route_maps/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_route_maps.yaml

sonic_route_maps: Add 'set tag' functionality and sync argpec/module/model files
- Update the argspec, module, config, and facts files to support the route map 'set tag' option.
- Expand regression and unit test cases to test the new functionality.
- Update the 'module' file to synchronize option descriptions, "EXAMPLES", and other documentation items with the corresponding content in the 'argspec' file and in the "model" repo.
|N/A |
sonic_route_maps
[route_map_2.5.0_regression_ summary_native_intf.zip](https://github.com/user-attachments/files/16114467/route_map_2.5.0_regression_.summary_native_intf.zip)
[route_map_2.5.0_regression_full_native_intf.zip](https://github.com/user-attachments/files/16114468/route_map_2.5.0_regressi …

sonic_route_maps: Add 'set tag' functionality; sync argpec, module, and model files

---

changelogs/fragments/403-lag-interface-evpn-ethernet-segment.yaml
plugins/module_utils/network/sonic/argspec/lag_interfaces/lag_interfaces.py
plugins/module_utils/network/sonic/config/lag_interfaces/lag_interfaces.py
plugins/module_utils/network/sonic/config/lldp_global/lldp_global.py
plugins/module_utils/network/sonic/facts/lag_interfaces/lag_interfaces.py
plugins/modules/sonic_lag_interfaces.py
tests/regression/roles/sonic_lag_interfaces/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_lag_interfaces.yaml
tests/unit/modules/network/sonic/test_sonic_lag_interfaces.py

This is to add evpn ethernet-segment support for LAG interface.
GitHub Issue #379 
sonic_lag_interfaces
[regression.log](https://github.com/user-attachments/files/16531877/regression.log)
[regression-2024-08-07-11-45-15.html.pdf](https://github.com/user-attachments/files/16531880/regression-2024-08-07-11-45-15.html.pdf)
Regression testing and lots of unit testing.

Add evpn ethernet-segment support for LAG interface

---

changelogs/fragments/428-l3-interfaces-default-dad-fix.yaml
plugins/module_utils/network/sonic/config/l3_interfaces/l3_interfaces.py

Changes made in SONiC for handling of default l3_interfaces IPv6 "dad" (duplicate address detection) configuration
have caused breakage in the enterprise_sonic l3_interfaces resource module. This breakage is evident in recent
regression test runs. It is caused by the fact that SONiC now represents a "deleted" IPv6 "dad" configuration as
an "active" (present) configuration with a value of "DISABLE". The previous SONiC handling for this attribute,
which represented deleted IPv6 "dad" configuration as "null" was consistent with handling of almost all
configuration options in SONiC and was compatible with our Ansible handling.
The new behavior caused failures in idempotency handling, resulting in sending of requests for configuration that was already present in cases where the configuration …

Fix l3_interfaces regression failures due to IPv6 default "dad" configuration

---

changelogs/fragments/431-l3-interfaces-fix-replaced-state.yaml
plugins/module_utils/network/sonic/config/l3_interfaces/l3_interfaces.py
tests/regression/roles/sonic_l3_interfaces/defaults/main.yml

Fix replaced state handling in l3_interfaces module.
| N/A |
- sonic_l3_interfaces
Regression report (with updated test cases)
- Without fix: [l3_interfaces_regression_report_before_fix.pdf](https://github.com/user-attachments/files/16599924/l3_interfaces_regression_report_before_fix.pdf)
- With fix: [l3_interfaces_regression_report.pdf](https://github.com/user-attachments/files/16599930/l3_interfaces_regression_report.pdf)

l3_interfaces - Fix replaced state handling

---

changelogs/fragments/441-system-downward-compatibility-fix.yaml
plugins/httpapi/sonic.py
plugins/module_utils/network/sonic/facts/poe/poe.py
plugins/module_utils/network/sonic/facts/sflow/sflow.py
plugins/module_utils/network/sonic/facts/system/system.py
plugins/module_utils/network/sonic/facts/vrfs/vrfs.py
plugins/module_utils/network/sonic/facts/vxlans/vxlans.py
plugins/module_utils/network/sonic/sonic.py
plugins/modules/sonic_api.py
tests/regression/roles/sonic_system/defaults/main.yml
tests/unit/modules/network/sonic/test_sonic_system.py

Modify the enterprise_sonic httapi plugin "edit_config" wrapper for invocation of the Ansible "send" utility to avoid playbook-aborting exceptions due to the unconditional "GET" REST API invocation done within the "system" resource module for the auditd and "ip loadshare hash" configuration. Modify this wrapper so that, when the new "suppress notification of exception" (suppr_ntf_excp) input flag is True, it returns a valid, but empty "response" for any GET request for which a "resource not found" (code '404') ConnectionError exception occurs instead of aborting the currently executing playbook with the ConnectionError exception. Because the auditd and "ip loadshare hash" configurations are only available in SONiC 4.4+, invoking these GETs on older versions of SONIC causes a …

Enable system auditd and ip loadshare hash downward compatibility

---

README.md
changelogs/fragments/446-README-documentation-links-fix.yaml
changelogs/fragments/446-system-documentation-links-fix.yaml

Ansible/Redhat has moved the location for automatically generated module documentation from a location in the "docs.ansible.com" domain to a new location in the "galaxy.ansible.com" domain. This change set modifies the module documentation links used in the README.md file for this resource module collection to use the new location instead of the deprecated old location. These changes are also intended to fix the module documentation links in the embedded, derived content for this resource module collection on the web page at "https://galaxy.ansible.com/ui/repo/published/dellemc/enterprise_sonic/docs/".
| |
N/A
README …

Fix broken module documentation links in the README.md file

---

changelogs/fragments/456-tests-sanity-ignore-action-plugin-for-ansible-2.19.yaml
tests/sanity/ignore-2.19.txt

When Ansible deploys a new core release, the sanity matrix test for the new core release flags an error for the "sonic.py" action plugin because there is no corresponding resource module containing documentation. To work around the flagging of these misleading sanity errors, we have placed an "ignore" file for each Ansible core version in our "tests/sanity" folder. The new Ansible core 2.19 release has just been deployed, so this PR provides the corresponding "ignore" file for that release.
| |
N/A
tests
```paste below
```
```paste below
```
Please describe the tests that you ran to verify your changes. Please also list …

Add a sanity "ignore" file for the new Ansible core version 2.19.

---

changelogs/fragments/460-stp-long-int-vlan-fix.yaml
plugins/module_utils/network/sonic/config/stp/stp.py
tests/regression/roles/sonic_stp/defaults/main.yml
tests/regression/roles/sonic_stp/tasks/preparation_tests.yaml
tests/unit/modules/network/sonic/fixtures/sonic_stp.yaml

A utility function used in this resource module for converting incoming vlan IDs and vlan ranges for use in REST APIs used an incorrect criterion for distinguishing an individual vlan ID from a vlan range. It assumed that the length of the incoming "vlan_id" string would be 1 for an individual vlan and longer for a range. As a result, it failed to correctly recognize an individual vlan ID with more than one digit. Because the "problem" cases were all handled by this shared function, a simple fix in this utility function is sufficient for fixing the problem in the cases where it would have occurred.
| |
N/A
sonic_stp
STP …

Allow handling of vlan ID values containing more then one digit.

---

changelogs/fragments/466-ospf-area-bugfix.yaml
plugins/module_utils/network/sonic/config/ospf_area/ospf_area.py

Fixed bug in delete method where there was no condition handling the case of no requests to delete.
sonic_ospf_area
failing report:
[regression-2024-10-10-13-44-49.html.pdf](https://github.com/user-attachments/files/17335364/regression-2024-10-10-13-44-49.html.pdf)
Passing report after change:
[regression-2024-10-10-14-42-02.html.pdf](https://github.com/user-attachments/files/17334607/regression-2024-10-10-14-42-02.html.pdf)

Ospf area bugfix

---

README.md

`ansible_pass` doesn't exist and is a typo for `ansible_password`, as used everywhere else expect in the README.
N/A
README.md

Fix ansible_password typo

---

changelogs/fragments/470-interfaces-speed-bugfix.yaml
plugins/module_utils/network/sonic/config/interfaces/interfaces.py

I removed the conditional error message for speed configuration because it was incorrectly restricting speed configuration.
| GitHub Issue #467  |
[regression-2024-10-15-16-12-55.html.pdf](https://github.com/user-attachments/files/17386747/regression-2024-10-15-16-12-55.html.pdf)
Failing playbook before fixing bug:
[failing_playbook.log](https://github.com/user-attachments/files/17386750/failing_playbook.log)
Passing playbook after fixing bug:
[passing_playbook.log](https://github.com/user-attachments/files/17386752/passing_playbook.log)

Remove conditional error message for speed configuration in sonic_interfaces

---

changelogs/fragments/471-fix-vxlan-regression-tests.yaml
tests/regression/roles/sonic_vxlan/defaults/main.yml
tests/regression/roles/sonic_vxlan/tasks/cleanup_tests.yaml
tests/regression/roles/sonic_vxlan/tasks/main.yml
tests/regression/roles/sonic_vxlan/tasks/preparation_tests.yaml

Fix the failing vxlan regression tests
N/A
sonic_vxlan
[suppress_vlan_neigh.html.pdf](https://github.com/user-attachments/files/17467273/suppress_vlan_neigh.html.pdf)
[suppress_vlan_neigh.txt](https://github.com/user-attachments/files/17467278/suppress_vlan_neigh.txt)

Fix failing regression tests for vxlan

---

changelogs/fragments/474-l3_interfaces-ipv6-autoconf-downward-compatibility.yaml
plugins/module_utils/network/sonic/config/l3_interfaces/l3_interfaces.py
tests/regression/roles/sonic_l3_interfaces/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_l3_interfaces.yaml

Some of the changes made in the l3_interfaces resource module for support of new SONiC 4.4.0 IPv6 features in "https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/374" were implemented in a way that was not downward compatible with older versions of SONiC. These changes resulted in customer playbook failures when using this resource module on older SONiC images (e.g. SONiC 4.1.6). The failures were caused by unnecessary sending of REST APIs containing new SONiC 4.4.0 options with default values in some "replaced" and "overridden" state cases.
| |
N/A
sonic_l3_interfaces
Example of a playbook that …

Modify SONiC 4.4.0 IPv6 feature support code to eliminate failures on older versions of SONiC.

---

changelogs/fragments/464-REST-server-cipher-suite.yaml
plugins/module_utils/network/sonic/argspec/mgmt_servers/mgmt_servers.py
plugins/module_utils/network/sonic/config/mgmt_servers/mgmt_servers.py
plugins/module_utils/network/sonic/facts/mgmt_servers/mgmt_servers.py
plugins/modules/sonic_mgmt_servers.py
tests/regression/roles/sonic_mgmt_servers/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_mgmt_servers.yaml

**SUMMARY**
Resource module changes for REST server cipher suite.
**ISSUE TYPE**
**COMPONENT NAME**
sonic_mgmt_servers
**RELATED PR**
https://github.com/ansible-network/resource_module_models/pull/276
**OUTPUT**
[regression-2024-10-08-13-37-18.html.pdf](https://github.com/user-attachments/files/17290516/regression-2024-10-08-13-37-18.html.pdf)
[mgmt_servers_config_UT_check_mode.log](https://github.com/user-attachments/files/17290520/mgmt_servers_config_UT_check_mode.log)
Scaled version of [regression-2024-10-08-13-37-18.html.pdf](https://github.com/user-attachments/files/17470500/regression-2024-10-08-13-37-18.html.pdf)
**Checklist:**

Ansible support for REST server cipher suite configuration

---

changelogs/fragments/508-tacacs-server-bugfix.yaml
changelogs/fragments/509-tacacs-server-bugfix.yaml
plugins/module_utils/network/sonic/config/tacacs_server/tacacs_server.py

I added a sleep in the config file to allow TACACS server config updates to apply to SONiC PAM modules.
sonic_tacacs_server
Failing regression report before change:
[regression-2025-02-17-13-46-50.html.pdf](https://github.com/user-attachments/files/18833448/regression-2025-02-17-13-46-50.html.pdf)
Passing regression report after change:
[regression-2025-02-17-13-52-45.html.pdf](https://github.com/user-attachments/files/18833451/regression-2025-02-17-13-52-45.html.pdf)

Add sleep to allow TACACS server config updates to apply to SONiC PAM modules

---

changelogs/fragments/526-l2-interfaces-bugfix.yaml
plugins/module_utils/network/sonic/config/l2_interfaces/l2_interfaces.py
plugins/modules/sonic_l2_interfaces.py
tests/unit/modules/network/sonic/fixtures/sonic_l2_interfaces.yaml

SONiC doesn't allow specification of a list for trunk-vlans deletion so I updated the module code for l2 interfaces accordingly.
sonic_l2_interfaces
[regression-2025-03-12-15-08-46.html.pdf](https://github.com/user-attachments/files/19218776/regression-2025-03-12-15-08-46.html.pdf)

Fix VLAN deletion bug for L2 interfaces module

---

changelogs/fragments/537-logging-severity-bugfix.yaml
plugins/module_utils/network/sonic/config/logging/logging.py

Fixing issue #508 where if severity was "None" in the sonic_logging attribute the module would throw a traceback error.
| GitHub Issue #508 |
sonic_logging
```paste below
"after": {
"anycast_address": {
"ipv4": true,
"ipv6": true,
"mac_address": "00:09:5B:EC:EE:F2"
},
"audit_rules": "BASIC",
"auto_breakout": "ENABLE",
"concurrent_session_limit": 4,
"hostname": "SONIC-ov",
"interface_naming": "standard"
},
"before": {
"anycast_address": {
"ipv4": true,
"ipv6": false
},
"audit_rules": "DETAIL",
"auto_breakout": "DISABLE",
"hostname": "sonic",
"interface_naming": "native"
},
"commands": [
{
"anycast_address": {
"ipv6": false
},
"state": "deleted"
},
{
"anycast_address": {
"mac_address": "00:09:5B:EC:EE:F2"
},
"audit_rules": "BASIC",
"auto_breakout": "ENABLE", …
```

Usr/austin.whaley issue-508 sonic logging bugfix for severity attribute

---

changelogs/fragments/494-LDAP-security-profile-task.yaml
tests/regression/roles/sonic_ldap/defaults/main.yml
tests/regression/roles/sonic_ldap/tasks/cleanup_tests.yaml
tests/regression/roles/sonic_ldap/tasks/preparation_tests.yaml

Crypto security-profile is required before configuring ldap security-profile.
Added a new preparation task to configure crypto security profile.
| N/A |
- sonic_ldap
**Regression report:**
[regression-2024-12-18-14-03-07.pdf](https://github.com/user-attachments/files/18177390/regression-2024-12-18-14-03-07.pdf)

Add preparation tasks for LDAP security profile

---

changelogs/fragments/546-image-management-location_change.yaml
tests/regression/roles/sonic_image_management/tasks/preparation_tests.yml

Change the location of the SONiC image zip file used by this regression test from the "/tmp" directory location to the "permanent" directory "/usr/local/share/script_files". This change is being made to avoid aborting of the test suite due to periodic and event-driven erasure of the /tmp directory on the test server.
| |
N/A
sonic_image_management
[image_management_location_change_test_summary.pdf](https://github.com/user-attachments/files/19743402/image_management_location_change_test_summary.pdf)
To test this change, I copied the target ".zip" file from the specified location on the SONiC Ansible test server to an …

Use a permanent instead of "tmp" location for the SONiC image zip file used by the image_managment regression test.

---

changelogs/fragments/555-Logging-Security-Profile-Ansible-Support.yaml
plugins/module_utils/network/sonic/argspec/logging/logging.py
plugins/module_utils/network/sonic/config/logging/logging.py
plugins/module_utils/network/sonic/facts/logging/logging.py
plugins/modules/sonic_logging.py
tests/regression/roles/sonic_logging/defaults/main.yml
tests/regression/roles/sonic_logging/tasks/cleanup_tests.yaml
tests/regression/roles/sonic_logging/tasks/preparation_tests.yaml
tests/unit/modules/network/sonic/fixtures/sonic_logging.yaml

Update Enterprise SONiC 'logging' resource module for syslog security profile command:
Provide updated data definitions in 'argspec'.
Implement updated 'facts' to gather facts for the module.
Implement updated 'config' to apply configurations for merged, deleted, replaced and overridden states.
Define updated regression and unit test cases to verify correct functionality of logging security profile for syslog.
Regression LOG:
[SONIC_LOGGING_REGRESSION.pdf](https://github.com/user-attachments/files/20200333/SONIC_LOGGING_REGRESSION.pdf)
GitHub Issue # NA
- sonic_logging 
**Ansible Lint logs:**
```
(ansible) …
```

Add Dell Collection changes for Syslog security profile

---

changelogs/fragments/561-bgp-nbr-af-documentation.yaml
plugins/modules/sonic_bgp_neighbors_af.py

I fixed typos in the configuration examples for BGP neighbors AF.
sonic_bgp_neighbors_af

Fix typos in configuration examples for BGP neighbors AF

---

changelogs/fragments/564-lag-interfaces-regression-test-fix.yaml
changelogs/fragments/565-lag-interfaces-regression-test-fix.yaml
tests/regression/roles/common/defaults/main.yml

I updated the interface variables in the common defaults main.yml to use lower Ethernet ports since port groups are only supported for  Ethernet ports 0-95 on the device used for regression. The lag interfaces regression was failing due to using Ethernet ports out of this range.
tests/regression/roles/common/defaults/main.yml
Failing report before changes:
[regression-2025-06-10-14-18-24.html.pdf](https://github.com/user-attachments/files/20680423/regression-2025-06-10-14-18-24.html.pdf)
Passing report after changes:
[regression-2025-06-10-14-20-55.html.pdf](https://github.com/user-attachments/files/20680425/regression-2025-06-10-14-20-55.html.pdf)

Fix LAG interfaces regression failure

---

changelogs/fragments/569-vrfs-bugfix.yaml
playbooks/common_examples/mgmt_vrf_config.yaml
playbooks/common_examples/mgmt_vrf_off.yaml
plugins/module_utils/network/sonic/config/vrfs/vrfs.py
plugins/modules/sonic_vrfs.py

I fixed a  VRFs bug for overridden state.
sonic_vrfs
[regression-2025-06-19-10-50-46.html.pdf](https://github.com/user-attachments/files/20823893/regression-2025-06-19-10-50-46.html.pdf)

Fix VRFs bug for overridden state

---

changelogs/fragments/577-mirroring-regression-test-fix.yaml
tests/regression/roles/sonic_l2_interfaces/defaults/main.yml
tests/regression/roles/sonic_l2_interfaces/meta/main.yaml
tests/regression/roles/sonic_l2_interfaces/tasks/cleanup.yaml
tests/regression/roles/sonic_l2_interfaces/tasks/main.yml
tests/regression/roles/sonic_l2_interfaces/tasks/preparation_tests.yaml
tests/regression/roles/sonic_l2_interfaces/tasks/tasks_template.yaml
tests/regression/roles/sonic_mirroring/tasks/preparation_tests.yaml

I fixed the mirroring regression test failures. I also added cleanup for L2 interfaces as well as resolved ansible-lint errors for L2 interfaces
sonic_mirroring
sonic_l2_interfaces
Native interface naming mode test report:
[regression-2025-08-05-13-17-06.html.pdf](https://github.com/user-attachments/files/21607519/regression-2025-08-05-13-17-06.html.pdf)
Standard interface naming mode test report:
[regression-2025-08-05-13-31-18.html.pdf](https://github.com/user-attachments/files/21607535/regression-2025-08-05-13-31-18.html.pdf)
Updated report:
[regression-2025-08-07-12-25-51.html.pdf](https://github.com/user-attachments/files/21671872/regression-2025-08-07-12-25-51.html.pdf)
- [] I have maintained at least 90% code coverage
- [] I have commented my code, …

Fix mirroring regression test failures

---

changelogs/fragments/583-bgp-nbr-auth-pwd-bugfix.yaml
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml

I fixed a bug for 'auth_pwd' that was preventing  'pwd' to be updated after initial configuration. In SONiC, in order to modify auth-password both password and encrypted are needed. The argspec reflects this, as 'pwd' is required and 'encrypted' is defaulted to false. The issue is that when calculating the diff if one option changed and the other option didn't change from the existing configuration then the 'get_diff' utility method filters out the unchanged option as expected. Therefore I created a 'get_diff_bgp_nbr'  method that will keep the unchanged option in the diff for auth_method when the other option is changed. For all states/configuration, 'pwd' and 'encrypted' should be present together therefore I removed the default entry in config file for encrypted for the …

Fix BGP neighbors auth_pwd bug

---

changelogs/fragments/584-test-reports-reduced-logging.yaml
tests/regression/roles/common/tasks/action.facts.report.yaml
tests/regression/roles/common/tasks/all.facts.summary.report.yaml
tests/regression/roles/common/tasks/cli.contains.test.facts.report.yaml
tests/regression/roles/common/tasks/cli.test.facts.report.yaml
tests/regression/roles/common/tasks/idempotent.facts.report.yaml
tests/regression/roles/common/tasks/single.run.facts.report.yaml
tests/regression/roles/test_reports/tasks/all_tasks_log_template.yaml
tests/regression/roles/test_reports/tasks/main.yml

Background:
The current enterprise_sonic Ansible regression logging mechanism generates a huge volume of console log
data because of the order "n-squared" logging algorithm it uses. Each test subsection generates and prints to the console the "set_facts" log for itself plus every test subsection that preceded it. Now that we have 82 modules with an average of ~26+ test sections (including "action" plus "idempotent" sections), the number of test sections is > 2000, and the current "order 4,000,000" log size created by the redundant, "recursive" logging is taking more time and storage space than our test server environment can support. This has reached a critical level where most full regression test runs abort due to insufficient storage space.
Changing the logging algorithm to log the …

Change redundant order n-squared regression test logging to non-redundant order "n" logging.

---

changelogs/fragments/586-bgp-allowas_in-option-mutual-exclusion-change.yaml
plugins/module_utils/network/sonic/argspec/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/argspec/bgp_neighbors_af/bgp_neighbors_af.py
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py
plugins/module_utils/network/sonic/config/bgp_neighbors_af/bgp_neighbors_af.py
plugins/module_utils/network/sonic/utils/bgp_utils.py
plugins/module_utils/network/sonic/utils/utils.py
plugins/modules/sonic_bgp_neighbors.py
plugins/modules/sonic_bgp_neighbors_af.py
tests/regression/roles/sonic_bgp_neighbors/defaults/main.yml
tests/regression/roles/sonic_bgp_neighbors_af/defaults/main.yml
tests/unit/modules/conftest.py
tests/unit/modules/network/sonic/fixtures/sonic_bgp_neighbors.yaml
tests/unit/modules/network/sonic/fixtures/sonic_bgp_neighbors_af.yaml

In response to customer requests, this change set removes the overly strict mutual exclusion between the two defined options for the BGP neighbor and peer_group address family "allowas_in" dictionary. For the two options, an 'origin' option value of "false" is, with this change set, permitted at the same time as a non-null 'value' option. (A "true" value for the 'origin' option remains incompatible with specifying a 'value' because only one of these two conflicting criteria can be configured. An 'origin' value of "true" allows only one occurrence of the AS for "this" BGP instance; as the origin of the route, while a 'value', instead, allows up to a specified number of occurrences of this AS in the AS_PATH.)
This change set make the following changes for the affected BGP files:
- argspec …

Remove mutual exclusion for BGP 'allowas_in' options.

---

changelogs/fragments/591-mclag-bugfix.yaml
plugins/module_utils/network/sonic/config/mclag/mclag.py
plugins/module_utils/network/sonic/facts/mclag/mclag.py
tests/regression/roles/sonic_mclag/defaults/main.yml
tests/unit/modules/network/sonic/fixtures/sonic_mclag.yaml

I fixed the domain ID creation bug which now enables users to create a domain ID with no other attributes specified. Because of current SONiC behavior it's necessary to use REST method put for initial domain ID creation to ensure the configuration gets configured on the device in all cases.
sonic_mclag
[regression-2025-10-06-16-01-34.html.pdf](https://github.com/user-attachments/files/22732252/regression-2025-10-06-16-01-34.html.pdf)

Fix domain ID creation bug for mclag module
